### ISSUE TITLE
Introductory Meeting

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#1]
We held our first meeting and introduced ourselves. In addition to meeting and getting to know each other we also assigned some initial tasks to each other.

### Attendees
- [x] Ali Başaran
- [ ] Alperen Bırçak
- [X] Arda Kabadayı
- [X] Bilal Atım
- [X] Can Uzduran
- [X] Çisel Zümbül
- [X] Deniz Ünal
- [X] Ege Ekşi
- [X] Halis Bal
- [ ] Harun Sami Çelik
- [X] Mehmet Said Yolcu
- [X] Zeynep Baydemir

@AliBasarann can you add further details?

**Comment by AliBasarann** [comment]
## Notes
We met at zoom and we introduced ourselves. First subject of the meeting is determining a communication platform other than Whatsapp. The team members decided that Discord is the best platform that we can use. After solving the communication problem, we talked about weekly task. The team members thought that a common template for the personal information pages of the team members would be better than doing it individually. Then, team members decided that determining a meeting notes template and issue tags would be good too for the our repository. The team members also thought that an additional and informal task assignment platform is necessary. 

### Weekly Issues
- [ ] Creating a discord group and setting up discord channels
- [ ] Designing a template for personal information page
- [ ] Designing a template for meeting notes
- [ ] Creating and designing issue tags
- [ ] Deciding an additional task assignment platform
- [ ] Creating a personal information page (everyone)
- [ ] Researching a repository (everyone)

**Comment by Ardakacd** [comment]
Thank you for the notes @AliBasarann. I'm closing the issue.
