### ISSUE TITLE
Creating User Scenario For Creates An E-Sport Event

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#102]
### Description

I prepared create event and detailed event mockups in #53  and #54 issue. As a result of the task distribution we made as a team, me and my teammate harun sami took the task of Creating User Scenario For Creates An E-Sport Event. User scenario should be descriptive and clear.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

09.04.2023 - Sunday - 23.59

**Comment by harunsami** [comment]
We uploaded the  **"User Scenario For Creates An E-Sport Event"** page to github wiki. 
@said-yolcu  can you check it with this [link](https://github.com/bounswe/bounswe2023group5/wiki/User-Scenario-For-Creates-An-E-Sport-Event)?

**Comment by said-yolcu** [comment]
I have reviewed **User Scenario For Creating An E-Sport Event**. I have returned my evaluation to @harunsami .

**Comment by harunsami** [comment]
We have read the review report which @said-yolcu send us and update the page. 
@said-yolcu can you check the updated page?

**Comment by said-yolcu** [comment]
I have checked the updated page. Nice work @harunsami  and @bilalatim . The **User Scenario for Creating an E-sport Event** is very explanatory and meets all the requirements. I am **closing** this issue and marking it as **Done**.
