### ISSUE TITLE
Designing Sequence Diagram: Promotion

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#103]
### Description

The sequence diagrams are shared among group members. My job is to design the sequence diagram for promotion functionality.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

11.04.2023 - Pazar - 23.59

**Comment by said-yolcu** [comment]
I have designed the **Sequence Diagram for Promotion** and sent it to @halisbal. @halisbal can you review it and inform me of your evaluation of it?

**Comment by halisbal** [comment]
I reviewed your sequence diagram and send you couple of feedbacks about forum promotions. In overall, nice work! I can check again when you finalize the work.

**Comment by said-yolcu** [comment]
I have updated **Promotion Sequence Diagram** according to your feedback and sent to you. Can you check it again @halisbal ?

**Comment by halisbal** [comment]
Now I checked and everything looks perfect. Thank you for considering my feedbacks. Good work! Since you are done with the task, I am closing this issue.
