### ISSUE TITLE
 Adding Contributions of Deniz Ünal

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#104]
### Description

Everyone is responsible for adding a Individual Contribution Report to the Milestone report. I will add the summary of my contributions under the Contributions page in order to help me while creating my report.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

10.04.2023 Monday 23.59

**Comment by Ardakacd** [comment]
I reviewed your contributions page. It is clear and detailed. Hence I'm closing the issue.
