### ISSUE TITLE
adding image annotation backend

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#1045]
### Description

Currently we can only annotate texts, I will also add image annotation feature.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

23.12.2023

**Comment by halisbal** [comment]
I reviewed your [PR](https://github.com/bounswe/bounswe2023group5/pull/1083) and merged, nice work! Since this task is done, I am closing this issue.
