### ISSUE TITLE
Profile Game Store Account Link Fix

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#1048]
### Description

Seems like game store accounts linked to the profile don't redirect users to a correct page. I will checkout the problem and fix it.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

24.12.2023

**Comment by cisel-zumbul** [comment]
@halisbal I think you showed me the bug, however I couldn't reproduce it. Can you give some details?

**Comment by halisbal** [comment]
I checked the frontend again and realized that I didn't give a valid input when I encountered this problem. There is absolutely no problem with valid inputs. Nice work!

**Comment by cisel-zumbul** [comment]
Ok @halisbal,thanks for the feedback. Then I'm closing this issue as there is no need for development.
