### ISSUE TITLE
Evaluation of Deliverables 1

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#106]
### Description

The deliverables of Milestone 1 are shared among team members. I will do List and Status of Deliverables part together with @egeek259. I will do evaluation of project repository, requirements, communication plan, project plan & RAM.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

10.04.2023 Monday 23.59

**Comment by egeek259** [comment]
I have reviewed your work , It was detailed and nicely written , therefore I'm closing the issue.
