### ISSUE TITLE
Create Private Group Bug Fix

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#1068]
### Description

The private group cannot be created due to some error. There is a problem at membership policy field. I will try to fix that.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

23.12.2023

**Comment by cisel-zumbul** [comment]
I might have missed it in the PR above, however when I checked this in main, I was still having the same issue. I couldn't create private group. Can you please have a look at it again?

**Comment by AliBasarann** [comment]
I fixed it and it is merged to main. I am closing the issue.
