### ISSUE TITLE
Merging All Sequence Diagrams Into One

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#107]
### Description

Each member of the team prepared individual part of the sequence diagram of the project. Now we need to merge them into one main sequence diagram.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by canuzdrn** [comment]
All sequence diagrams can be viewed via visiting [here](https://github.com/bounswe/bounswe2023group5/wiki/Sequence-Diagram).

**Comment by Ardakacd** [comment]
Thank your for your contributions. It has been done very well. Hence I'm closing the issue.
