### ISSUE TITLE
Writing Evaluation of Tools and Processes That We Have Used to Manage Our Team Project Section for Our Milestone Report

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#108]
### Description

Our milestone report needs to include a section called "Evaluation of tools and processes that you have used to manage your team project". I will be writing this part of the milestone report. This section will include the tools we've used throughout our development process and how did we manage our team and kept our workflow organized and collabrative.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by canuzdrn** [comment]
"Evaluation of Tools and Processes" section of our milestone report can be visited [here](https://github.com/bounswe/bounswe2023group5/wiki/Milestone-1-Report).

**Comment by said-yolcu** [comment]
I reviewed the **Evaluation of Tools and Processes** section of the milestone report that you have created. Good job. It covers all the major tools and processes we have used for development of our project. I am closing this issue and marking it as **Done**.
