### ISSUE TITLE
Deciding on an Additional Brainstorming Platform and Designing a Template

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#11]
An additional brainstorming platform is needed in order to track the ideas. Using GitHub issues as brainstorming is inefficient, because issues page can be very complicated if we add the ideas that would not be applied to real life. The candidate platforms are:
- Trello 
- Notion
- Excel

We should also create a initial basic template so that we can start to use the platform. The necessary topics that we should add to the template are:
- Ideas
- Issue candidates
- Issues

**Comment by alperen-bircak** [comment]
I propose we use Trello as the "brainstorming" platform.

**Comment by AliBasarann** [comment]
I believe that trello is the best option that we can use. If there is no objection, we can set up the trello page.

**Comment by AliBasarann** [comment]
The trello page is setted up. I am closing the issue.
