### ISSUE TITLE
Evaluation of Deliverables 1

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#111]
### Description

The deliverables of Milestone 1 are shared among team members. I will do List and Status of Deliverables part together with @UnalDeniz . I will do evaluation of Scenarios and Mockups, and Software Design Documents in UML.
.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

10.04.2023 - Monday - 23:59

**Comment by UnalDeniz** [comment]
I have reviewed your work. Good job, it was nicely written. I'm closing this issue.
