### ISSUE TITLE
Writing Unit Test Reports

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#1129]
### Description

I will write unit test reports for final milestone deliverables.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

29.12.2023

**Comment by zeynep-baydemir** [comment]
It can be reached from [here](https://github.com/bounswe/bounswe2023group5/wiki/Unit-Test-Reports)

**Comment by halisbal** [comment]
Nice work! I reviewed your work and didn't see any problem. It looks quite detailed and well organized, thank you! Since this task is done, I am closing this issue.
