### ISSUE TITLE
User Manual - Register and Login

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#1137]
### Description

I will add the parts related to register and login functionalities in our user manual.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

29.12.2023

**Comment by canuzdrn** [comment]
Register/Login section of the user manual is ready, one can review the register/login section via visiting [here](https://github.com/bounswe/bounswe2023group5/wiki/User-Manual).

**Comment by UnalDeniz** [comment]
Since the report is already completed, I am closing this issue.
