### ISSUE TITLE
User Manual - Recommendations

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#1139]
### Description

I will add the parts related to game and group recommendation functionalities in our user manual.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

29.12.2023

**Comment by canuzdrn** [comment]
Recommendation section of the user manual is ready, one can review the recommendation section via visiting [here](https://github.com/bounswe/bounswe2023group5/wiki/User-Manual).

**Comment by Ardakacd** [comment]
I reviewed it. It seems good.
