### ISSUE TITLE
User Manual - Promotion

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#1140]
### Description

I will add the parts related to game promotion functionality in our user manual.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

29.12.2023

**Comment by canuzdrn** [comment]
Promotion section of the user manual is ready, one can review the promotion section via visiting [here](https://github.com/bounswe/bounswe2023group5/wiki/User-Manual).

**Comment by Ardakacd** [comment]
I reviewed it. It seems good.
