### ISSUE TITLE
Final Report - API Documentation

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#1141]
### Description

I will be preparing a detailed API documentation of our REST API and add the documentation to the final report.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

29.12.2023

**Comment by canuzdrn** [comment]
API documentation is prepared. One can review overall API documentation via visiting [here](https://github.com/bounswe/bounswe2023group5/wiki/API-Documentation).

**Comment by AliBasarann** [comment]
Thanks for your contributions, I am closing the issue.
