### ISSUE TITLE
Final Report - Individual Report

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#1142]
### Description

I'm going to add my *"Individual Report"* to *"Final Report"*

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

29.12.2023

**Comment by canuzdrn** [comment]
My individual report is ready, to review it in detail one can visit [here](https://github.com/bounswe/bounswe2023group5/wiki/Contributions-of-Can-Uzduran-%E2%80%90-451).

**Comment by Ardakacd** [comment]
I reviewed it. It seems good.
