### ISSUE TITLE
User Manual - Post/Comment/Profile

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#1144]
### Description

I will add the parts related to post, comment and  profile in our user manual.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

29.12.2023

**Comment by zeynep-baydemir** [comment]
I added post, comment and profile user manuals, it can be reached by [here](https://github.com/bounswe/bounswe2023group5/wiki/User-Manual).

**Comment by UnalDeniz** [comment]
Since the report is already completed I am closing this issue.
