### ISSUE TITLE
Provide Progress According To Requirements For Final Milestone

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#1148]
### Description

As a part of the final milestone deliverables, I will create a table showing requirements and the current status of each requirement (not started, in progress, or done) on the project.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

29.12.2023

**Comment by bilalatim** [comment]
I am closing this issue, since you have completed your task,
