### ISSUE TITLE
Write Summary Of Work Performed By Backend Team Members

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#1151]
### Description

I will add summary of work performed by backend team members in final deliverables

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

29.12.2023

**Comment by zeynep-baydemir** [comment]
It can be reached from [here](https://github.com/bounswe/bounswe2023group5/wiki/Summary-Of-Work)

**Comment by canuzdrn** [comment]
It's a detailed documentation of what each member has work-wise accomplished throughout semester, thanks for the tidy work
