### ISSUE TITLE
Designing Sequence Diagram: Review

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#116]
### Description

Sequence diagrams are shared among team members. I will design the sequence diagram for Review.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

10.04.2023 - Monday - 23:59

**Comment by Ardakacd** [comment]
I reviewed your sequence diagram for Review. It is clear and detailed. Hence I'm closing the issue.
