### ISSUE TITLE
Writing the Introduction/Project Description for Milestone Report

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#119]
### Description

I was tasked with writing the Introduction/Project Description part for the milestone report.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

10.04.2023

**Comment by alperen-bircak** [comment]
I have added the text to our milestone page, can you review it @cisel-zumbul ?

**Comment by cisel-zumbul** [comment]
I think it is comprehensive enough, I have nothing more to add. Good job, I'm closing the issue.
