### ISSUE TITLE
Creating Personal Information Page

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#12]
Every member of the team should create a personal information page using [Personal Information Page Template](https://github.com/bounswe/bounswe2023group5/wiki/Personal-Information-Page-Template).

### Assignees

- [x] Ali Başaran
- [x] Alperen Bırçak
- [x] Arda Kabadayı
- [x] Bilal Atım
- [x] Can Uzduran
- [x] Çisel Zümbül
- [x] Deniz Ünal
- [x] Ege Ekşi
- [x] Halis Bal
- [ ] Harun Sami Çelik
- [x] Mehmet Said Yolcu
- [x] Zeynep Baydemir

**Comment by halisbal** [comment]
The deadline for this task has passed, hence I am closing this issue.

**Comment by Ardakacd** [comment]
A quick note about this issue: we created this issue before we talked about how to create good issues. So, after this issue we tried to divide issues into at most 4 assignees instead of creating a checkbox for assignees in the description.
