### ISSUE TITLE
Project Plan For Milestone 1

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#120]
### Description

The deliverables of **Milestone 1** are shared among team members. I will create a documentation for **Project Plan** and also create a **Gantt Chartt** representing it.

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

11.04.2023 - Tuesday - 23:59

**Comment by said-yolcu** [comment]
I created a **Project Plan** for **Milestone 1**. But Because of the time constraints I gave up creating a **Gantt Chartt**. @zeynep-baydemir , can you review my work?

**Comment by zeynep-baydemir** [comment]
Thank you for your effort. I'm closing this issue.
