### ISSUE TITLE
Analyzing and brain storming possible requirements for the group finding feature

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#14]
We need to analyze the provided requirements document to develop our understanding of the group finding feature. We may also think of other requirements that are not in the document, but we believe are fitting for the project. 

   The findings will be put into the Trello page as concise sentences under the "Group Finding" list.

**Comment by cisel-zumbul** [comment]
I added couple of items that come to my mind. Also checked yours, they were good!

**Comment by alperen-bircak** [comment]
Thanks, the new items look great. We can close the issue before the PS

**Comment by cisel-zumbul** [comment]
Since we've completed this step and filled up the Trello page, I'm closing this issue. Continuing with #29.
