### ISSUE TITLE
Setting Up the Basic Front-End Environment for Practice App

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#149]
### Description

We will use react for creating the front-end for our practice app, so I will create a basic react application as a starting point.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

04.05.2023

**Comment by alperen-bircak** [comment]
Initial setup can be found on frontend-setup branch, pending review

**Comment by bilalatim** [comment]
I'm closing this issue because the frontend setup has been merged.
