### ISSUE TITLE
Adding Meeting Notes #8

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#156]
### Description

I was the note taker of the meeting 8 (27.04.2023). I will upload the notes of the meeting to the wiki page and clarify what we decided and did during the meeting. [Meeting note template](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-Note-Template) will be used to be consistent.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

04.05.2023

**Comment by cisel-zumbul** [comment]
I've added the meeting notes. You can check it from [here](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-%238-Notes-(27.04.2023)).

**Comment by alperen-bircak** [comment]
They look great! keep up the good work.
