### ISSUE TITLE
Setting Up Back-End Environment for Practice App

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#158]
### Description

We will use nodejs for creating the back-end for our practice app, so I will create a initial setup for our nodejs application. This initial setup should include 

- creating a index.js file to startup our api
- creating connection with remote database
- creating error templates 

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

06.05.2023

**Comment by Ardakacd** [comment]
I forgot to mention that response template should also be created.

**Comment by halisbal** [comment]
I checked the initial setup from our repository, everything looks good. Since we are done with this part, I am closing this issue.
