### ISSUE TITLE
Creating a Remote Database in Aws 

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#159]
### Description

In this task I will deploy a remote mongo db database to a aws server using mongo atlas.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

06.05.2023

**Comment by Ardakacd** [comment]
@canuzdrn I give you permission to access our remote database. Can you check whether there is an error about the deployment, if not can you close the issue.

**Comment by canuzdrn** [comment]
I've tested database connection via remote access and viewed success message for database connection. Hence, everything seems fine in terms of deployment. Since Arda is done with deployment of our database in an AWS Server, I'm closing this issue.
