### ISSUE TITLE
Adding Meeting Notes #9

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#168]
### Description

I was the note taker of the meeting 9 (04.05.2023). I will upload the notes of the meeting to the wiki page and clarify what we decided and did during the meeting. [Meeting note template](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-Note-Template) will be used to be consistent.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

09.05.2023 - Tuesday - 23:59

**Comment by egeek259** [comment]
I've added the meeting notes. You can check it from [here](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-%239-Notes-04.05.2023).

**Comment by cisel-zumbul** [comment]
It seems good, thanks. Closing this issue.
