### ISSUE TITLE
Creating the Schema of MongoDb GameByCategory Collection for Practice App: Arda Kabadayı

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#173]
### Description

In this task I will create a schema of my GameByCategory collection in mongodb. The schema should include the following fields:

- [x] game id
- [x] email
- [x] title
- [x] short description
- [x]  genre
- [x]  platform
- [x] publisher
- [x]  developer
- [x] release date
- [x] timestamps

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

07.05.2023

**Comment by zeynep-baydemir** [comment]
I have reviewed your code and looked your instances in the database. Since everything seems nice I am closing this issue. Thank you for your effort and good work.
