### ISSUE TITLE
Creating a User Login Page for Improved App Functionality

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#178]
### Description

To improve the functionality of our app, we have determined that it would be beneficial to include a user login page. This page will prompt users to enter their email address, which will then be used as a unique identifier to display only their individual history of requests. By implementing this feature, users can easily track their previous requests, making it a more practical and convenient experience.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

06.05.23

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
