### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Can Uzduran

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#181]
### Description

In this task I will implement a "POST /card" endpoint. This endpoint will basically do the following: based on the given category, make a request to the [Hearthstone API](https://rapidapi.com/omgvamp/api/hearthstone/) and insert the response to the database to the designated schema/table. For detailed functionality the steps will be:

- [x] Get the given card name or id
- [x] Check whether the card name or id is valid
- [x] Make a request to [Hearthstone API](https://rapidapi.com/omgvamp/api/hearthstone/) "Single Card" endpoint based on the given card name or id
- [x] Get the response
- [x] Parse the response and insert the desired values to database such as card name, card id , card set/collection etc.
- [x] Return a success message if everything is fine
- [x] Return an error message if an error occurs in previous steps

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

09.05.2023

**Comment by cisel-zumbul** [comment]
I noticed that the CardByNameController.js file has an API key hard-coded into it. That could be risky for security reasons, so it'd be great if you could remove it. As we discussed in the meeting, it would be perfect if you could add it as an environment variable instead. Thanks for taking care of this!

**Comment by canuzdrn** [comment]
@cisel-zumbul  You may check pull request #192. If everything seems fine you may also close this issue

**Comment by cisel-zumbul** [comment]
Everything looked fine to me now, I reviewed and merged your PR. Thanks for quick response :)
