### ISSUE TITLE
Improving Functionality with PostFunction Attribute Integration in API Data

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#189]
### Description

To enhance the user experience and increase functionality, integrating a postFunction attribute to the apidata is crucial. This added feature allows users to easily write and add their own post function to be used with the formbuilder component.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

07.05.2023

**Comment by AliBasarann** [comment]
The integration is very good. I am closing the issue.
