### ISSUE TITLE
Creating the Schema of MongoDb GameReview Collection for Practice App: Çisel Zümbül

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#191]
### Description

In light of our decision to include a user request history feature in our practice application, it is necessary for me to develop a MongoDB schema for storing game reviews. This schema will be used specifically for each user to see their previously fetched game reviews.

- [x] user email
- [x] game name
- [x] game id
- [x] review list (consisting 3 reviews per request) 
      reviews having structure:
     - [x]  review text
     - [x]  publish date 
- [x] request time

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

09.05.2023

**Comment by halisbal** [comment]
I checked your work and approved the pull request. Good job! Since your task is done, I am closing this issue.
