### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Çisel Zümbül

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#193]
### Description

In this task I will implement a "POST /review" endpoint. This endpoint will take in a user-provided game name, make a request to the [OpenCritic API](https://rapidapi.com/opencritic-opencritic-default/api/opencritic-api/)'s 'Game Search' endpoint to find the corresponding game ID and use that ID to fetch the reviews for the game issuing another request to the 'Reviews for Game' endpoint. After fetching them, it will insert the first three reviews in a designated database table.

For detailed functionality the steps will be:

 - [x] Get the given game name
 - [x] Make a request to [OpenCritic API](https://rapidapi.com/opencritic-opencritic-default/api/opencritic-api/)'s 'Game Search' based on the given game name
 - [x] Parse the response and get the game ID
 - [x] Make a request to [OpenCritic API](https://rapidapi.com/opencritic-opencritic-default/api/opencritic-api/)'s 'Reviews for Game' using the game ID fetched from previous call's response
 - [x] Parse the response, create a review list from reviews having snippets and their game id matching the id provided with the request
 - [x] Create database objects with three reviews, user email, game name and game id 
 - [x] Insert objects to the database 
- [x] Return a success message if each step is completed as intended
- [x] Return an error message if an error occurs in previous steps

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

09.05.2023

**Comment by Ardakacd** [comment]
I reviewed your work. It is good. So I'm closing the issue.
