### ISSUE TITLE
Configuration of Backend URLs in Frontend Development in .env File

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#198]
### Description

In modern web development, it is essential to separate the frontend and backend layers. The frontend codebase should communicate with the backend server via an API. One best practice is to get the backend URL from an environment variable instead of hardcoding it into the frontend code. This approach ensures flexibility and ease of maintenance while avoiding potential security vulnerabilities. By adopting this method, frontend developers can easily switch between different environments without making changes to the codebase.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

08.05.2023

**Comment by AliBasarann** [comment]
Good work. Since we finished frontend work, I am closing the issue.
