### ISSUE TITLE
Fixing the Unique Key Warning in JsonViewer Component

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#199]
### Description

The React JsonViewer component is a useful tool for displaying JSON data in a visually appealing way. However, when rendering arrays, it emits a unique key warning, which can cause performance issues and potential bugs. To fix this issue, we need to add a unique key prop to each child element of the array. This can be achieved by mapping over the array and assigning a unique identifier to each item. By addressing this warning, we can ensure a smoother user experience and reduce the risk of errors.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

09.05.2023

**Comment by AliBasarann** [comment]
I read the [documetation](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key) . In React, each element in a list should have a unique "key" prop. This helps React keep track of the elements and improve performance when rendering and updating the list.

To solve the "each child in a list should have a unique key prop" error, I added a "key" prop to each child element in the list with a unique value.

**Comment by AliBasarann** [comment]
I also saw the same warnings at form builder component and I fixed it as well. Can you review it @alperen-bircak

**Comment by AliBasarann** [comment]
The branch is reviewed and merged by alperen, so I am closing the issue.
