### ISSUE TITLE
Creating Personal Information Page Template

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#2]
We decided that every personal information page must follow the same design pattern. Therefore a personal information page template is needed.

The Personal Information page template should include:

- Name
- Surname
- Photo
- Brief description
- Skills
- Interests
- Contacts (GitHub, LinkedIn, Mail)

@alperen-bircak can you create this template?

**Comment by alperen-bircak** [comment]
The page has been created, pending review.

**Comment by Ardakacd** [comment]
@alperen-bircak thank you for the design! Can you also add the link of the page for easy access. After that I will close the issue.

**Comment by cisel-zumbul** [comment]
@alperen-bircak Can you add the interests section, too?

**Comment by alperen-bircak** [comment]
Interests section has been added. You can reach the page from the sidebar of the wiki, or [here](https://github.com/bounswe/bounswe2023group5/wiki/Personal-Information-Page-Template).
