### ISSUE TITLE
Adding Notes of Meeting #2

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#20]
As the note taker for our previous weekly meeting (09.03.2023), my task is to create a comprehensive summary of Meeting 2 and upload it to our project's Github repository. I will follow the meeting notes template of our team. I will include the key topics discussed, decisions made, and action items assigned in the meeting notes. Additionally, I will ensure that the notes are organized in a clear and concise manner, making it easy for team members to review and reference when needed. This task is critical to ensure that everyone is on the same page and can follow up on any action items assigned during the meeting.

**Comment by canuzdrn** [comment]
Halis, it is apparent that your task is still in progress, however I've seen that **moderator** section is empty in second meeting notes. Arda Kabadayı was the moderator for that particular meeting. I just wanted to ask/remind you to edit the meeting note page in case it just escape your notice. Other details looks okay, thanks for the great work !

**Comment by halisbal** [comment]
Thanks for bringing that up @canuzdrn, I updated the page as you mentioned.

With that progress, meeting notes for Meeting 2 is completed. Therefore I'm closing this issue. You can find the meeting notes in our homepage, sidebar and [here](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-%232-Notes-09.03.2023).
