### ISSUE TITLE
Improve the Aesthetics of Frontend

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#200]
### Description

To improve the aesthetics of our frontend, we need to focus on key design elements such as typography, color schemes, and layouts. We should also consider incorporating responsive design principles to ensure our application looks great across different devices and screen sizes. By enhancing the visual design of our frontend, we can create a better app.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

09.05.2023

**Comment by bilalatim** [comment]
I reviewed your work. The frontend looks better now. Good job. I am closing the issue.
