### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Halis Bal

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#203]
### Description

In this task I will implement a "POST /suggestion" endpoint. This endpoint will take in a user-provided prompt which should be describing user's game taste and user's email, then make a request to the ChatGPT endpoint to get suggestions from AI. To use ChatGPT for free, I will use Retool API. Retool will be handling the ChatGPT request. 

For detailed functionality the steps will be:
- [x] Get the prompt and email from the body of the request
- [x] Check whether the request input is valid
- [x] Make a request to Retool API using constant system prompt and given user prompt
- [x] Get the response and insert to the database
- [x] Return appropriate response message

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

08.05.2023

**Comment by UnalDeniz** [comment]
I've checked your work. Endpoint works at it should be. I'm closing this issue.
