### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Deniz Ünal

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#204]
### Description

In this task I will implement a "POST /user" endpoint. This endpoint will take in a user-provided prompt which should be a steamid and user's email, then make a request to the GetOwnedGames endpoint to get the games owned by the user corresponding to the steamid. Returned data will be added to the database.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

08.05.2023

**Comment by halisbal** [comment]
Good work! Since your development is merged, I am closing this issue.
