### ISSUE TITLE
Implementing a Get Endpoint for Practice App: Deniz Ünal

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#205]
### Description

In this task I will implement a "GET /user" endpoint. This endpoint will basically do the following: based on the given user's email, it will return the history of the responses(these responses are stored in our database) that the user get from  POST /user endpoint. 

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

08.05.2023

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
