### ISSUE TITLE
Implementing a Post Endpoint for Practice App

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#210]
### Description

In this task I will implement a "POST /freegames" endpoint. Makes a request to the [Epic Free Games](https://rapidapi.com/1yesari1/api/epic-free-games) and insert the response to the database. 
Steps:

- [x] get user's email from the body of the request.
- [x] check validity of user email
- [x] make a request to [external api](https://epic-free-games.p.rapidapi.com/epic-free-games)
- [x] parse the response and insert the needed values to database.
- [x] return a success message if response succesfully added to database.
- [x] return an error message if an error occurs in any step.

 

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

09.05.2023

**Comment by zeynep-baydemir** [comment]
I had to change my api because it doesn't give response always. I am using [esport api](https://rapidapi.com/fluis.lacasse/api/esportapi1). My endpoint is 'https://esportapi1.p.rapidapi.com/api/esport/tournament/categories'.

**Comment by Ardakacd** [comment]
I reviewed your work. It is good. So I'm closing the issue.
