### ISSUE TITLE
Implementing a Get Endpoint for Practice App

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#211]
### Description

I will implement a "GET /freegames" endpoint. Based on the user's email, it will return the history of the responses that the user get from [Epic Free Games Api](https://rapidapi.com/1yesari1/api/epic-free-games).

Steps:

- [x] get the user's email from the query parameters.
- [x] check email validity
- [x] get the necessary rows from the database based on the given user's email.
- [x] return these rows.
- [x] give an error message if an error occurs in previous steps.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

09.05.2023

**Comment by zeynep-baydemir** [comment]
I had to change my api because it doesn't give response always. I am using [esport api](https://rapidapi.com/fluis.lacasse/api/esportapi1).

**Comment by bilalatim** [comment]
I reviewed your work. Your GET function works fine. Good job. I am closing the issue.
