### ISSUE TITLE
Enhancement Request for JSONViewer Component: Updating on Form Submit and Page Change

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#219]
### Description

The current implementation of the JSONViewer component lacks the ability to update on form submit and page change events, leading to inconsistencies in data representation. We propose an enhancement that allows the component to dynamically refresh when these events occur. This would improve the user experience and ensure accurate representation of data at all times.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

10.05.23

**Comment by AliBasarann** [comment]
I handled the refresh event when the page is changed
