### ISSUE TITLE
Enhancing FormBuilder Component with New Input Field Types

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#220]
### Description

As part of my ongoing effort to improve the functionality of the FormBuilder component, I will be adding two new input field types - boolean and number. This will provide other members with greater flexibility when designing forms, enabling them to create more complex and customized inputs. 

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

10.05.23

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Nice job! Since this task is done, I am closing this issue.
