### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Ali Başaran

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#221]
### Description

In this task I will implement a "POST /AchievementPercentages" endpoint. This endpoint will basically do the following: based on the given game id, make a request to the [Steam Api](https://developer.valvesoftware.com/wiki/Steam_Web_API) and insert the top 3 achievements that have been done to the database. For detailed functionality the steps will be:

- [x] Get the given gameid and user's email  from the body of the request.
- [x] Check whether the gameid and user's email  is valid. 
- [x] Make a request to [Steam Api](https://developer.valvesoftware.com/wiki/Steam_Web_API) "/ISteamUserStats/GetGlobalAchievementPercentagesForApp/v0002/?gameid=<game_id>" endpoint based on the given gameid.
- [x] Get the response.
- [x] Parse the response and insert the needed values to database.
- [x] Return a success message if everything is fine.
- [x] Return an error message if an error occurs in previous steps.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

10.05.2023

**Comment by canuzdrn** [comment]
Due to merging of #234 , I'm closing this issue.
