### ISSUE TITLE
Implementing a Get Endpoint for Practice App: Ali Başaran

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#222]
### Description

In this task I will implement a "GET /category" endpoint. This endpoint will basically do the following: based on the given user's email, it will return the history of the responses(**these responses are stored in our database**) that the user get from [Steam Api](https://developer.valvesoftware.com/wiki/Steam_Web_API), "/ISteamUserStats/GetGlobalAchievementPercentagesForApp/v0002/?gameid=<game_id>" endpoint. For detailed functionality the steps will be:

- [x]  Get the user's email from the query parameters.
- [x]  Check whether the user's email  is valid.
- [x]  Get the necessary rows from the database based on the given user's email.
- [x]  Return these rows.
- [x]  Return an error message if an error occurs in previous steps.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

10.05.2023

**Comment by Ardakacd** [comment]
I reviewed your job. It seems okay.
