### ISSUE TITLE
Implementing a Get Endpoint for Practice App: Bilal Atım

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#223]
### Description

In this task I will implement a "GET /genre/genreID" endpoint. This endpoint will basically do the following: based on the given user's email, it will return the history of the responses(these responses are stored in our database) that the user get from [Rawg Video Games Api](https://rawg.io/apidocs), "api/genres/{genreID} =<genre ID>?key=<rawg_Api_Key>" endpoint. 

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

10.05.2023 - Wednesday - 23.59

**Comment by bilalatim** [comment]
I have implemented and pushed https://github.com/bounswe/bounswe2023group5/pull/310 the GET endpoint for /api/genre. Can you check my work @egeek259 ?

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
