### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Bilal Atım

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#226]
### Description

In this task I will implement a "POST /genres/{genreID}" endpoint. This endpoint will basically do the following: based on the given genreID, make a request to the [RAWG Video Games Api](https://rawg.io/apidocs) and insert the response to the database.  To use Api user need a key. I got api key from oficial web page by signing up. For detailed functionality the steps will be:

For detailed functionality the steps will be:

- [x] Get the given genreID, key and user's email from the body of the request.
- [x] Check whether the genre, key and user's email is valid.
- [x] Make a request to [RAWG Video Games Api](https://rawg.io/apidocs) "api/genres/{genreID}=<genreID>?key=<Rawg api key>" endpoint based on the given category.
- [x] Get the response.
- [x] Parse the response and insert the needed values to database.
- [x] Return a success message if everything is fine.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

10.05.2023 - Wednesday - 23.59

**Comment by bilalatim** [comment]
I have implemented and pushed #310  the POST endpoint for /api/genre. Can you check my work @egeek259 ?

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
