### ISSUE TITLE
Creating The NavBar Component For Practice App

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#227]
### Description

As a developer, my objective is to create a dynamic Navigation Bar component that can efficiently generate a list of pages based on a specified JavaScript object. By leveraging the power of React, I aim to build a scalable and customizable solution that provides a seamless user experience while optimizing development time and code quality.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

10.05.2023 - Wednesday - 23.59

**Comment by bilalatim** [comment]
With #255 I fixed The input text overlapping the NavBar bug.

**Comment by AliBasarann** [comment]
I reviewed your work. The navbar seems good. I am closing the issue.
