### ISSUE TITLE
Creating the Schema of MongoDb GameByCategory Collection for Practice App: Ali Başaran

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#228]
### Description

In this task I will create a schema of my GameByCategory collection in mongodb. The schema should include the following fields:

- [x] game id
- [x] email
- [x] least completed achievement
- [x] second least completed achievement
- [x] third least completed achievement
- [x] timestamps

All achivements will contain following fields:
- [x] name
- [x] success rate

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

10.05.2023

**Comment by UnalDeniz** [comment]
Good job, closing this issue.
