### ISSUE TITLE
Creating GameByCategory Frontend Page

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#230]
### Description

In this task I will create GameByCategory page using the steps described in [here](https://github.com/bounswe/bounswe2023group5/wiki/Practice-App-Frontend-Documentation). 

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

11.05.2023

**Comment by bilalatim** [comment]
I reviewed your work. Your Frontend Page provides the necessary requirements. I am closing the issue.
