### ISSUE TITLE
Implementing a Get Endpoint for Practice App: Çisel Zümbül

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#237]
### Description

In this task I will implement a "GET /review" endpoint. This endpoint will basically do the following: based on the given user's email, it will return the history of the responses(these responses are stored in our database) that the user get from [OpenCritic Api](https://rapidapi.com/opencritic-opencritic-default/api/opencritic-api/), "../reviews/game/{gameid}" endpoint. For detailed functionality the steps will be:

 - [x] Get the user's email from the query parameters.
 - [x] Check whether the user's email is valid.
 - [x] Get the necessary rows from the database based on the given user's email.
- [x] Return these rows.
 - [x] Return an error message if an error occurs in previous steps.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

12.05.2023

**Comment by canuzdrn** [comment]
Since I've reviewed (and approved) your PR (#241), and concluded that your GET endpoint works fine, I'm closing this issue.
