### ISSUE TITLE
Creating Unit Tests for Achievement Endpoint

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#239]
### Description

I will create unit tests for my endpoint to make sure that the endpoints working as expected. For this purpose, I will use JEST as our team decided.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

11.05.2023

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
