### ISSUE TITLE
Implementing a Get Endpoint for Practice App: Ege Ekşi

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#247]
### Description

In this task I will implement a "GET /yugiohcard" endpoint. Given user email as a URL parameter, this endpoint will return the data from yugiohcard collection from the MongoDB database which are matching that user email. These data will include inserted objects via POST /yugiohcard endpoint just like a response history.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

12.05.2023

**Comment by halisbal** [comment]
I checked your work, it looks good! And since your code is merged, I am closing this issue.
