### ISSUE TITLE
Writing Unit Tests For Game Review Endpoints

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#252]
### Description

I will write unit tests for POST ../review/ and GET ../review/.. endpoints that I've implemented to make sure that the endpoints are working as expected. For this purpose, JEST will be used as our team decided.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

12.05.2023

**Comment by UnalDeniz** [comment]
Your tests work correctly, closing this issue.
