### ISSUE TITLE
Creating GameSuggestions Frontend Page

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#253]
### Description

In this task I will design the Game Suggestions page using the steps described in [here](https://github.com/bounswe/bounswe2023group5/wiki/Practice-App-Frontend-Documentation).

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

11.05.2023

**Comment by AliBasarann** [comment]
Good work. I am closing the issue.
