### ISSUE TITLE
Writing Unit Tests For Game Suggestion Endpoints

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#254]
### Description

I will be implementing unit tests for POST ../suggestion/ and GET ../suggestion/.. endpoints that I've developed to make sure that the endpoints are working as expected. For this purpose, JEST will be used as our team decided.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

12.05.2023

**Comment by canuzdrn** [comment]
Your tests were well written and functionality-wise they were error-free. Thanks for the good work.
