### ISSUE TITLE
Hiding Unnecessary Fields in Frontend

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#261]
### Description

Some fields that come from backend are displayed in frontend such as _id and createdAt properties. They should be hidden from the users.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

11.05.2023

**Comment by halisbal** [comment]
Nice work! Since I reviewed your pull request and merged your code, I am closing this issue.
