### ISSUE TITLE
Updating GameSuggestions API

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#265]
### Description

In the first version of the game suggestions API, POST endpoint was requiring only a user prompt. When I develop the frontend of the game suggestions page, I realized that only one input is not enough. I decided that the user input should contain two fields: enjoyed_games and preferred_game_type.
Then my API should put these information in the prompt and get the response. To do that, I will update the controller functions and MongoDB schema.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

11.05.2023

**Comment by Ardakacd** [comment]
I reviewed your work. It is good. So I'm closing the issue.
