### ISSUE TITLE
Creating Template For API Documentation

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#273]
### Description

I will create a page that includes a **template** for API documentation, so that other team members can create their API documentation pages for Practice App using that template.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

12.05.2023 - Friday - 23.59

**Comment by said-yolcu** [comment]
I have created a template for **API documentation** . @egeek259 can you review it?

**Comment by egeek259** [comment]
I have reviewed this issue. Everything seems perfect. Therefore , I am closing this issue.
