### ISSUE TITLE
Writing Unit Tests For Endpoints 

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#275]
### Description

I will write unit tests for POST ../tournaments and GET ../tournaments endpoints that I've implemented to make sure that the endpoints are working successfully. I will use Jest and Supertest libraries as our team decided.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

12.05.2023

**Comment by cisel-zumbul** [comment]
Related is pr is merged, therefore closing this issue.
