### ISSUE TITLE
Designing Frontend Page for Esport Tournaments 

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#277]
### Description

In this task I will design the Esport Tournaments page using the steps described in [here](https://github.com/bounswe/bounswe2023group5/wiki/Practice-App-Frontend-Documentation).

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

12.05.2023

**Comment by alperen-bircak** [comment]
This clearly works, good job. This issue shouldve been closed earlier, better late than never.
