### ISSUE TITLE
Writing Unit Tests For CardByName Endpoints

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#278]
### Description

I will write unit tests for POST /card/ and GET /card/ endpoints that I've implemented to make sure that the endpoints are working as expected. For this purpose, **Jest** and **Supertest** libraries will be used as our team decided.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

12.05.2023

**Comment by Ardakacd** [comment]
I reviewed your work and pr. They seems okay. So I'm closing the issue.
