### ISSUE TITLE
Implementing a Get Endpoint for Practice App: Harun Sami Çelik

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#279]
### Description

In this task I will implement a "GET /rock-paper-scissors/choice" endpoint. This endpoint will basically do the following: based on the given choice, it will return the history of the responses(these responses are stored in our database) that the user get from [Rock Paper Scissors API](https://rapidapi.com/mer747/api/rock-paper-scissors13), "rock-paper-scissors13.p.rapidapi.com/?choice=<choice>" endpoint.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by harunsami** [comment]
I have implemented and pushed https://github.com/bounswe/bounswe2023group5/pull/319 the GET endpoint for /api/genre. Can you check my work @bilalatim ?

**Comment by bilalatim** [comment]
I reviewed your work. Your GET function works. I am closing the issue.
