### ISSUE TITLE
Game Id to Game Name Convertion for Achievements Endpoint

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#280]
### Description

I found a package that converts steam game id's to game names. I will use it to convert steam game id's and I will store the names of the games as well.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

12.05.2023

**Comment by AliBasarann** [comment]
I used [this](https://github.com/lucakiebel/appid) package when converting the game id to game name.

**Comment by UnalDeniz** [comment]
Good job.
