### ISSUE TITLE
Implementing A Get Endpoint For Practice APP

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#284]
### Description

Each team member must implement a **Get endpoint**. I will implement a **Get endpoint** for top games.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by cisel-zumbul** [comment]
We've merged and tested this, everything seems fine. Good job. Closing this issue.
