### ISSUE TITLE
Implementing A Post Endpoint For Practice APP

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#285]
### Description

Each team member must implement a **Post endpoint**. I will implement a **Post endpoint** for **top games**.

### 👮‍♀️ Reviewer

Harun Sami Çelik

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by harunsami** [comment]
I reviewed your work. POST function works. I am closing the issue.
