### ISSUE TITLE
Formalizing the Requirements of the Feature: Groups

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#29]
As follow-up issue to issue #14, now we should formalize the requirements that we've added to Trello page.

Requirements should be categorized as **functional/non-functional** and **user/system** requirements.
While formalizing the requirements, use :
**shall**, for the features that we should certainly have
**should**,  for the features that are not necessarily a must

After a formal requirement draft is created, these requirements should be discussed with the team and also with our PO before they are put in the wiki page.

**Comment by cisel-zumbul** [comment]
I formalized the requirements and changed some 'should's into shall in order to comply with the general conventions as it was discussed with the team.  You can find the latest version in the wiki page. Next, we need to add couple of group requirements about application notification process of groups. @alperen-bircak

**Comment by alperen-bircak** [comment]
I have added the new requirements. I think the requirements are in a great place right now, we can always revise later if needed. I'll go ahead and close this task.
