### ISSUE TITLE
Multiple Tests Trying to Connect the Same Port

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#294]
### Description

When running multiple tests all of them trying to connect the same port. I will try to fix it.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

12.05.2023

**Comment by AliBasarann** [comment]
I solved this issue by seperating by connecting the server and exporting the app in different files.

**Comment by Ardakacd** [comment]
I reviewed your job. It seems okay.
