### ISSUE TITLE
Deployed frontend can not reach backend

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#295]
### Description

When the docker images are pulled from the AWS and run from there, back-end and front-end runs separately without issue. But front-end cannot reach API from the back-end. I will try to fix it
This bug is related to #262.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

12.05.2023

**Comment by cisel-zumbul** [comment]
Hello, can you check [here](https://www.tutorialworks.com/container-networking/). To summarize, it says docker containers creates their own network for communication and we should use their containers' ip in order to provide container to container communication.

**Comment by UnalDeniz** [comment]
> Hello, can you check [here](https://www.tutorialworks.com/container-networking/). To summarize, it says docker containers creates their own network for communication and we should use their containers' ip in order to provide container to container communication.

Thanks, I will have a look at it.

**Comment by cisel-zumbul** [comment]
Let me know if you need any help

**Comment by UnalDeniz** [comment]
It seems the problem was caused by the mis-configured environment variables.  @alperen-bircak found the problem. No code change required, closing the issue.
