### ISSUE TITLE
Frontend Aesthetic Additions

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#302]
### Description

I will add two new functionalities to frontend:
* dataTitle field in apipadata so that other members can add titles at the top of the jsonViewer.
* Turn keys that have an underscore in them to capitalized keys that look better. (ex: "user_email" to "User Email")

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

12.05.2023

**Comment by cisel-zumbul** [comment]
I appreciate the effort and attention to detail that went into implementing the changes we've discussed together for the UI design. Thank you. It works well, therefore, closing this issue.
