### ISSUE TITLE
Creating a Documentation Page for Card By Name API

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#308]
### Description

I will create a documentation page for Card By Name API that I've implemented using an external API called [Hearthstone API - Single Card](https://rapidapi.com/omgvamp/api/hearthstone/). Throughout my documentation process I'll be following steps described [here](https://github.com/bounswe/bounswe2023group5/wiki/API-Documentation-Template).

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

12.05.2023

**Comment by canuzdrn** [comment]
One may view documentation page from [here](https://github.com/bounswe/bounswe2023group5/wiki/API-Documentation-for-Practice-App---Card-By-Name).

**Comment by halisbal** [comment]
I checked your documentation, good work! Since your task is done, I am closing this issue.
