### ISSUE TITLE
Implementing Tests for Genre Endpoints

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#312]
### Description

I have been tasked with implementing automated testing for **genre** endpoints. To achieve this objective, I will be utilizing the Supertest framework, which offers a powerful suite of testing tools designed to ensure comprehensive endpoint coverage and optimal functionality. By conducting these tests, we hope to mitigate potential issues while providing our users with a seamless and reliable experience.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

12.05.2023 - Friday - 23.59

**Comment by egeek259** [comment]
I have reviewed your issue. Your tests have been merged. Therefore , I'm closing this issue.
