### ISSUE TITLE
Creating Game By Genre Frontend Page

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#313]
### Description

In this task I will design the Games By Genre page using the steps described in [here](https://github.com/bounswe/bounswe2023group5/wiki/Practice-App-Frontend-Documentation).

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

12.05.2023 - Friday - 23.59

**Comment by bilalatim** [comment]
I have created and send push request #314  for the Game By Genre Frontend Page. Can you check my work @egeek259 ?

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
