### ISSUE TITLE
Creating a Documentation Page for Achievements by Game Id API

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#320]
### Description

I will create a documentation page for achievement endpoint of the api. I utilized [SteamWeb API](https://steamcommunity.com/dev) at my endpoint. User can post achievements of specific games and get achievements s/he posted.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

12.05.2023

**Comment by AliBasarann** [comment]
I wrote my documentation. You can access it [here](https://github.com/bounswe/bounswe2023group5/wiki/API-Documentation-for-Practice-App-Achievement-By-Game-Id) or from the sidebar.

**Comment by UnalDeniz** [comment]
Nice documentation. Closing this issue.
