### ISSUE TITLE
Preparing "Overall Status" Part of the Milestone Report

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#321]
### Description

I'll write a paragraph explaining the overall status of our practice app as it is asked in deliverables. After it is written it will be added to milestone report.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

12.05.2023

**Comment by said-yolcu** [comment]
I have reviewed **Overall Status** you wrote. Nice work. It meets all the requirements for such a report.
