### ISSUE TITLE
Creating Front-End Page For Top Games

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#324]
### Description

Each member will create the **front-end pages** for their respective routes using given infrastructure. I will create a **front-end page** for **Top Games**

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by egeek259** [comment]
I have reviewed your issue. Your pull request is reviewed and merged. Since this task is done, I am closing this issue.
