### ISSUE TITLE
Creating Individual Contribution Section for Milestone Report: Ali Başaran

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#332]
### Description

Every team member should write an individual contribution section explaining the part of the that is done by him in a detailed way. I'll write mine, create my wiki page and link it under contributions section in the milestone report.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

12.05.2023

**Comment by canuzdrn** [comment]
Your personal contributions page is well-written, thanks for the good work. Also, one can visit Ali's contributions section via visiting [here](https://github.com/bounswe/bounswe2023group5/wiki/Individual-Contribution-Section-Ali-Ba%C5%9Faran).
