### ISSUE TITLE
Creating Individual Contribution Section For Milestone 2: Mehmet Said Yolcu

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#335]
### Description

Each team member should create an **individual section** that includes the **contributions made by them for Practice App**.

### 👮‍♀️ Reviewer

Harun Sami Çelik

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by harunsami** [comment]
I checked your work. It seems good. I am closing the issue.
