### ISSUE TITLE
Creating Rock Paper Scissors Frontend Page

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#340]
### Description

In this task I will design the Games By Genre page using the steps described in [here](https://github.com/bounswe/bounswe2023group5/wiki/Practice-App-Frontend-Documentation).

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by harunsami** [comment]
I have created and send push request https://github.com/bounswe/bounswe2023group5/pull/319 for the Rock Paper Scissors Frontend Page. Can you check my work @bilalatim ?

**Comment by bilalatim** [comment]
I reviewed your work. The Frontend Page seems good. I am closing the issue.
