### ISSUE TITLE
Implementing Tests for Choice Endpoints

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#342]
### Description

I have been tasked with implementing automated testing for **choice** endpoints. To achieve this objective, I will be utilizing the Supertest framework, which offers a powerful suite of testing tools designed to ensure comprehensive endpoint coverage and optimal functionality. By conducting these tests, we hope to mitigate potential issues while providing our users with a seamless and reliable experience.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by bilalatim** [comment]
With this merge [#361 ](https://github.com/bounswe/bounswe2023group5/pull/361) you make your work. Good job. I close this issue.
