### ISSUE TITLE
Creating Individual Contribution Section for Milestone Report: Bilal Atım

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#349]
### Description

Every team member should write an individual contribution section explaining the part of the that is done by him in a detailed way. I'll write mine, create my wiki page and link it under contributions section in the milestone report.

### 👮‍♀️ Reviewer

Harun Sami Çelik

### ⏰ Deadline

12.05.2023 - Friday - 23.59

**Comment by bilalatim** [comment]
I wrote [Individual Contribution Section for Milestone Report](https://github.com/bounswe/bounswe2023group5/wiki/Individual-Contribution-Section-Bilal-At%C4%B1m). Can you check my work @harunsami ?

**Comment by harunsami** [comment]
I checked your work. Your report seems good. I am closing the issue.
