### ISSUE TITLE
Writing Unit Tests For Top Games Endpoints

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#355]
### Description

Each member will write **unit test** for their endpoints. I will write a **unit test for top games**

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

12.05.2023 - Friday - 23:59

**Comment by halisbal** [comment]
I reviewed your unit tests and merged your code. Good job! Since you are done with your task, I am closing this issue.
