### ISSUE TITLE
Adding Notes Of Meeting #10

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#364]
### Description

I was the note taker for [meeting 10](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-%2310-Notes-11.05.2023). I will create a wiki page and add its notes.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

20.05.2023 - Friday - 23:59

**Comment by said-yolcu** [comment]
@canuzdrn I have added the meeting notes. Can you check them

**Comment by canuzdrn** [comment]
Your meeting notes are well organized and content-wise everything seems okay, thanks for the good work.
