### ISSUE TITLE
Researching the domain specific elements

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#375]
### Description

Based on the feedback that are given to us in the last lab session, there is a need to do further research on domain specific elements regarding the project to make sure that our platform is not a general use platform. The research should be about determining the distinguishing factors of games.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

08.10.2023

**Comment by alperen-bircak** [comment]
Research and brainstorming as been done, recorded on [this wiki page.](https://github.com/bounswe/bounswe2023group5/wiki/Domain-Specific-Feature-Ideas)
