### ISSUE TITLE
Research sources and tools for front-end development

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#392]
### Description

We need to research the relevant technologies that should be used to develop the frontend part of our project. The main criteria are:

* Modern and useful to acquire the skills for.
* Fast and efficient to learn and appl
* Good developer experience.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

10.10.2023

**Comment by alperen-bircak** [comment]
A [wiki page](https://github.com/bounswe/bounswe2023group5/wiki/Frontend-Tech-Research) has been created. I suggest you write your findings in there too.

**Comment by bilalatim** [comment]
You can close this issue because the research topic has changed as my group's role is now in mobile development instead of front-end. @alperen-bircak

**Comment by alperen-bircak** [comment]
Alright, closng the issue.
