### ISSUE TITLE
Mobile Technology Research

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#399]
### Description

As part of the mobile team, I will conduct a research into the mobile technologies we can use, and add my research to the **mobile tech research** page.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

10.10.2023 - Tuesday - 12.00

**Comment by said-yolcu** [comment]
I have conducted some research and added my notes to the mobile tech page. @egeek259 can you review it? Thanks.

**Comment by egeek259** [comment]
I have reviewed your notes, everything seems fine. Closing the issue.
