### ISSUE TITLE
Mobile Technology Research

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#402]
### Description

As part of the mobile team, I will conduct a research into the mobile technologies we can use, and add my research to the **mobile tech research** page.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

10.10.2023 - Tuesday - 12.00

**Comment by bilalatim** [comment]
I have conducted some research about **Java** and added my notes to the mobile tech page. @said-yolcu can you review it? Thanks.

**Comment by said-yolcu** [comment]
I have looked at your review. Nice work. I am closing this issue and marking it as done.
