### ISSUE TITLE
Deciding The Mobile Technologies

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#411]
### Description

Deciding the technologies that will be used for the mobile development.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

11.10.2023 - Wednesday - 23.59

**Comment by harunsami** [comment]
We have decided to use Unity for mobile development.

**Comment by halisbal** [comment]
Since the technology that will be used in the mobile side of the application is decided, I am closing this issue.
