### ISSUE TITLE
Create a dockerfile for the back-end project and initialize the container

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#417]
### Description

We will containerize our backend project, and for this purpose we have decided on continuing using docker as we have some experience on it from the last semester. For this purpose we need to:
- Write a dockerfile
- Initialize the container
- Check if everything works correctly 

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

17.10.2023

**Comment by halisbal** [comment]
I reviewed the pull request and approved the changes. With the merge, docker file is added to our backend part of the repository. Since the task is done, I am closing this issue.
