### ISSUE TITLE
Creating An Initial 'Hello World' App For the Front-end Project

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#418]
### Description

After determining the technology for development and selecting the component library for styling the front-end of the project, we need to create an initially working 'Hello World'  app with the appropriate dependencies, including necessary libraries and tools.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

17.10.2023

**Comment by alperen-bircak** [comment]
I have created a basic application in the frontend-base branch, we can update and merge it when the technologies have been decided.

**Comment by canuzdrn** [comment]
Basis for the frontend part of the project is created, LGTM
