### ISSUE TITLE
Decide on Front-End Technologies

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#419]
### Description

We researched the technologies that are used at frontend development. We should discuss and decide on the technologies that will be used in front-end development

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

13.10.2023

**Comment by AliBasarann** [comment]
I prefer to use React. React is a free and open-source front-end JavaScript library for building user interfaces based on components. It has many advantages such as modularity and flexibility. In addition I select to use React because it has good documentation and large community. 

I also used React in my previous projects, so it would be better for me if we use React.

**Comment by cisel-zumbul** [comment]
Recently in my part-time work I have had the opportunity to develop UI components using React. I have conducted thorough research on React hooks and have gained confidence in my React skills. Also I like React because it has great documentation, and many people in the field use it, which makes it easier to solve problems and get help when needed. Therefore, I prefer React, too.

**Comment by Ardakacd** [comment]
We can also use Vue which is a popular JavaScript framework for building user interfaces. Its popularity, community support, developer-friendly features, and performance optimizations make it a strong choice for front-end projects. However, as I understand we are more familiar with React compared to Vue. So I would be okay for both of them.

**Comment by alperen-bircak** [comment]
I would also like to propose we use pnpm for package management. Its actively developed and is the fastest and most reliable choice in my experience.

**Comment by alperen-bircak** [comment]
I think the main technologies are decided, I will close this issue for now. If we change our min or there are any problems, we can reopen the issue.
