### ISSUE TITLE
Creating the mockup pages for group functionality

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#42]
### Description

    We need to create mockup pages concerning the group functionality. These pages should show how the user will interact with all the user requirements. There are three essential pages that should be created:
- [x] Group Browse Page
- [x] Individual Group Page
- [x] Group Creation PAge

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

23.59 28.03.23

**Comment by cisel-zumbul** [comment]
I've completed _Individual Group Page_ and _Group Creation Page_. You can check it from [here](https://www.figma.com/file/TYdt7pb3lAnogz93EcwSqb/352-Mockup?node-id=0-1&t=ICBzYpaCgrmw4db5-0), they're under Groups section. Also checked _Group Browse Page_ you've made and I think it reflects the requirements well.
