### ISSUE TITLE
Update/Redesign Class Diagrams

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#424]
### Description

In Cmpe 352 we created initial blueprint of our [class diagrams](https://drive.google.com/file/d/1eUX2Oc52HM9HID9TkQQOs0m939zgqa0R/view). We need to take a look at those, check if they are still correct and make sense. If necessary, we need update the existing class diagrams considering the [domain specific ideas](https://github.com/bounswe/bounswe2023group5/wiki/Domain-Specific-Feature-Ideas). This means we may need to  add new classes, methods or fields.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

17.10.2023

**Comment by alperen-bircak** [comment]
I handled the new game fields and the level/exp system. I think the reviewer for this issue could be @Ardakacd if its okay with you.

**Comment by zeynep-baydemir** [comment]
We handled the avatar class and updated related classes with @UnalDeniz.

**Comment by haliskunduz** [comment]
We created the achievement class diagram and redesigned the voting logic. We also connected our new classes and refactored vote class accordingly with @canuzdrn.

**Comment by Ardakacd** [comment]
I reviewed all the changes on the class diagrams. Now it fits more to our design. So I'm closing the issue.
