### ISSUE TITLE
Decide on a component library for styling the front-end project

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#425]
### Description

We need to decide on a component library to use for our frontend project. This is important to do early on because it is a vital part of any fontend application.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

17.10.2023

**Comment by alperen-bircak** [comment]
Ant Design (commonly known as antd) is like your reliable, Swiss Army knife of UI libraries. It's pretty comprehensive, offering a wide array of pre-built components that cover almost anything you could need for a project. It's kind of the middle ground between being developer-friendly and feature-packed. I propose we stick with it for our project.

**Comment by Ardakacd** [comment]
We can also use [Bootstrap](https://getbootstrap.com/) which is a powerful, extensible, and feature-packed frontend toolkit. By using Bootstrap, we can take advantage of pre-designed, customizable components and styles. In this way we can save a significant amount of time and effort. In addition, this framework offers a consistent and responsive grid system, a variety of CSS classes and utility functions, and a collection of ready-made design elements like buttons, forms, navigation bars, and more.

**Comment by AliBasarann** [comment]
I suggest to use Material-UI. Material-UI, a popular React framework, adheres to Google's Material Design guidelines, offering a modern and visually appealing design for web applications. It excels in providing a rich set of pre-built, responsive components with a component-based architecture, enabling rapid development while ensuring code reusability and maintainability. Material-UI has customization and theming capabilities. In addition, it has an active community  and well-written documentation.

**Comment by AliBasarann** [comment]
I suggested Material UI, yet based on the previous comments, I believe that the most appropriate library for us is antd.

**Comment by cisel-zumbul** [comment]
It seems we're leaning towards antd therefore I'm closing this issue
