### ISSUE TITLE
Decide on which platform to use for our milestones

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#426]
### Description

We need to look into Github Roadmap View and Project Libre, and decide on which one to use for our roadmap.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

11.10.2023

**Comment by alperen-bircak** [comment]
I have looked a bit into the github projects feature. While it is a bit buggy, I think it'll do the job.

**Comment by UnalDeniz** [comment]
I agree with you on GitHub projects feature. It gets integrated with our repository and everyone is familiar with using GitHub. Unless any good reasons otherwise, we should go with it.

**Comment by Ardakacd** [comment]
I also agree, github projects feature would be the best option for us. Because we handle almost of the management stuffs via github, also managing project plans/milestones by this feature would make our jobs easier.

**Comment by said-yolcu** [comment]
I have looked into Github Roadmap, and I cannot think of any reason not using it. It is quite practical. We should use it.

**Comment by alperen-bircak** [comment]
Then I'm marking this as resolved.
