### ISSUE TITLE
Determine our roadmap for our milestones

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#427]
### Description

We need to draw our roadmap with three milestones. These milestones should reflect how we plan to implement all the features that we plan to implement. The roadmap to the first milestone should be very clear, and the other milestones should be well defined as well.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

12.10.2023

**Comment by UnalDeniz** [comment]
I've checked the roadmap. All teams have done a great job. I'm closing the issue now.
