### ISSUE TITLE
Update/Redesign our requirements

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#428]
### Description

As the requirements have changed due to our decisions about new domain specific requirements, we should change the requirements to reflect the new state of the project. The features on [this list](https://github.com/bounswe/bounswe2023group5/wiki/Domain-Specific-Feature-Ideas) should be added, and the event requirements should be removed.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

17.10.2023

**Comment by cisel-zumbul** [comment]
We recently revised our requirements, expanded our achievements, and incorporated avatars in line with the [domain-specific ideas](https://github.com/bounswe/bounswe2023group5/wiki/Domain-Specific-Feature-Ideas) we came up with. Additionally, we had to make some trade-offs with certain features to ensure timely delivery of the project with these new additions.

**Comment by AliBasarann** [comment]
We've made the necessary changes to reflect the new domain-specific requirements and have added the specified features while removing the event-related requirements. I am closing this issue for now. If we will have to edit the requirements in the future, we will re-open this issue.
