### ISSUE TITLE
Create Initial Mobile App With Unity

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#431]
### Description

I will create an initial project for a mobile app development trial in Unity. To collaborate with my team members simultaneously, I will create a mobile development branch.

### 👮‍♀️ Reviewer

Arda

### ⏰ Deadline

15.10.2023 - Sunday - 12.00

**Comment by bilalatim** [comment]
I created the initial project with  [fab04f47648d1425a3cdcccf8408044d4bea9982] commit. @egeek259 can you check?

**Comment by Ardakacd** [comment]
I reviewed it and it seems a correct base for a unity project. So I'm closing the issue.
