### ISSUE TITLE
Configuring Database Connection

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#439]
### Description

Needless to say, we need a database for our project. I will be taking care of configuring MongoDb database connection of our project

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

24.10.2023

**Comment by Ardakacd** [comment]
I reviewed this [mr](https://github.com/bounswe/bounswe2023group5/pull/442). Database setup is configured correclty. So I'm closing the issue.
