### ISSUE TITLE
User Login/Logout Endpoints

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#447]
### Description

I will implement the login and logout endpoints and related unit tests.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

24.10.2023

**Comment by zeynep-baydemir** [comment]
I have implemented user login endpoint using JWT. We decided to handle the logout functionality in the frontend. Since @UnalDeniz reviewed my [pull request](https://github.com/bounswe/bounswe2023group5/pull/484), i am closing this issue.
