### ISSUE TITLE
Logout Functionality - FE

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#449]
### Description

I will implement the logout functionality for the web application of our project. The main steps of this task are:

- Creating a logout button or link within the user interface to initiate the logout process.
- After clicking the logout button, the user should be securely logged out.
- Ensuring that the user's session data is cleared, preventing any unauthorized access after logout.
- Redirecting the user to an appropriate page (e.g., a login page or a homepage) after successful logout.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

24.10.2023

**Comment by AliBasarann** [comment]
I implemented the logout functionality

**Comment by Ardakacd** [comment]
I reviewed this task. Logout functionality seems work correctly. So I'm closing the issue.
