### ISSUE TITLE
Register Page Implementation - MOBILE

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#452]
### Description

I will implement the register page and functionality for the mobile application of our project. The main steps of this task are:

- [x] Creating a register button within the user interface to initiate the register process.
- [x] Four Input box for user write his/her name, email, password and confirm password.
- [x] Login button for user already creaate an account.
- [x] Alternative register buttons.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

24.10.2023

**Comment by bilalatim** [comment]
I made the implementation of register page  with the following commits. Can you check @egeek259 ?
* d6ba64ab7e810ff2387881d8b6d93d81a1387e3d
* 5ad1c0214a4898d94d4614815608f53a1331c645

**Comment by egeek259** [comment]
I have checked the issue and the commits, nice job! Closing the issue.
