### ISSUE TITLE
Initial Home Page Implementation - MOBILE

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#453]
### Description

I will implement the initial home page and functionality for the mobile application of our project. The main steps of this task are:

- [x] A scroll rect to list our games.
- [x] A generic game prefabs to show games name, descriptions and other informations.
- [x] Commit button for games to create commit.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

24.10.2023

**Comment by bilalatim** [comment]
I made the initial home page with the following commits. Can you check @egeek259 ?
* fde9008a96e1b7c90a4954204e97d12a8312bc08  
* 37ee03fc773e4d8cbce8a0599e56b41f7d86a906
* 6d6c91a3199016db8a2b29e90fedf6fec8648d29
* 380ae4b94fda25e37ccf37982cdc9e14197de3b2

**Comment by egeek259** [comment]
I have checked the issue and the commits, everything seems fine. Closing this issue.
