### ISSUE TITLE
Initializing README document for Mobile - MOBILE

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#455]
As the mobile team, we decided to create a readme file with the contributions of team members in order to better understand our project. This task was assigned to all team members.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

31.10.2023

**Comment by said-yolcu** [comment]
We have forgot to close this issue. Its branch is already merged with pr #627 .

**Comment by said-yolcu** [comment]
I am closing this issue because the task is done.
