### ISSUE TITLE
Designing Class Diagram: User Activity

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#46]
### Description

There are plenty of classes in the class diagram. We shared the classes among the team. I will be responsible for the User Activity class diagram.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

07.04.2023

**Comment by cisel-zumbul** [comment]
I reviewed the class, good job, it covers almost everything. Only one thing I saw, I believe it may be a good idea o add a GameList attribute to the class to track followed games of a user.

**Comment by AliBasarann** [comment]
I added the games list that a user created and the functions related to it. Thanks for the review.

**Comment by AliBasarann** [comment]
I believe that the necessary changes are made according to entire design. There might be minor changes in the class attributes in future, yet the final design is made for now. Thanks to @cisel-zumbul for her contributions. I am closing the issue.
