### ISSUE TITLE
Login Web Page

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#461]
### Description

I will create a login page for our frontend app. It should contain header, login button and inputs in alignment with the  requirement 1.1.1.2.1. The functionality is as follows:

- A login page should be displayed for guest users.
-  Users shall provide their valid usernames(or email) and passwords to login.
- App should be redirected to home page.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

24.10.2023

**Comment by AliBasarann** [comment]
I reviewed the page and I like it. Its coherence with register page is perfect. I am closing the issue.
