### ISSUE TITLE
Logout Functionality For Mobile

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#463]
### Description

I will implement the logout functionality for mobile part of the project.

### 👮‍♀️ Reviewer

Harun Sami Çelik

### ⏰ Deadline

24.10.2023 - Tuesday - 23.59

**Comment by said-yolcu** [comment]
I have created the logout functionality. @harunsami can you close this issue.

**Comment by harunsami** [comment]
I have checked your work, nice job. I am closing this issue.
