### ISSUE TITLE
Register Web Page

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#464]
### Description

I will create a register page for our frontend app. It should contain header, register button and inputs in alignment with the  requirement 1.1.1.1. The functionality is as follows:

- A register page should be displayed for guest users.
-  Users shall provide their name, username, email, and passwords to register.
- After success, app should be redirected to home page.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

24.10.2023

**Comment by AliBasarann** [comment]
I reviewed the register page and I liked it. I am closing the issue.
