### ISSUE TITLE
Change Password Page For Mobile

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#465]
### Description

I will create a **Change Password** page for mobile part and implement the necessary functionality.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

24.10.2023 - Tuesday - 23.59

**Comment by said-yolcu** [comment]
I have created a Change Password Page for Mobile. @egeek259 can you check my page and close this issue?

**Comment by egeek259** [comment]
I have checked the page, everything seems fine. Closing the issue.
