### ISSUE TITLE
Forgot Password Page and Functionality Implementation For Mobile

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#466]
### Description

I will create a **Forgot Password** page for mobile part and implement the necessary functionality.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

24.10.2023 - Tuesday - 23.59

**Comment by said-yolcu** [comment]
I had already reviewed your work. Sorry for this delay. I am closing this issue and marking it as done.
