### ISSUE TITLE
Deciding on Color Palette of the Application

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#468]
### Description

Our application is in the process of design and development, and we need to establish a coherent and visually appealing color palette that aligns with our brand identity and enhances the user experience. A consistent color scheme not only improves aesthetics but also aids in usability and brand recognition. We will select a color palette to use.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

24.10.2023

**Comment by cisel-zumbul** [comment]
I really liked [this color palette](https://coolors.co/8ecae6-219ebc-023047-ffb703-fb8500-845a6d-a1e8af-f5ee9e). I really liked how balanced it is between vivid and pastel colors. It is also one of the most liked ones in the site [coolors](https://coolors.co/palettes/trending).

**Comment by AliBasarann** [comment]
I created [this color palette](https://coolors.co/ffbe0b-fd8a09-fb5607-fd2b3b-c11cad-a22acd-8338ec-3a86ff-6eb69b-a2e536) from the trending colors. I visualized the palette and this is the [link](https://coolors.co/visualizer/ffbe0b-fd8a09-fb5607-fd2b3b-c11cad-a22acd-8338ec-3a86ff-6eb69b-a2e536)

**Comment by Ardakacd** [comment]
I think [this color palette](https://coolors.co/palette/001219-005f73-0a9396-94d2bd-e9d8a6-ee9b00-ca6702-bb3e03-ae2012-9b2226) will be a good option for us. It uses different tones of a few color such as blue and red.

**Comment by alperen-bircak** [comment]
I think we should come up with a dark color palette, since gamers tend to hang out in the dark. I propose [this color palette](https://coolors.co/0a0a0a-ff47da-008dd5-d7263d-edf5fc). We should create a poll so at the whole team can vote.

**Comment by cisel-zumbul** [comment]
The poll results have spoken and we are going with my color palette, common sense wins once again!
