### ISSUE TITLE
Designing Class Diagram: Forum

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#47]
### Description

We decided on the classes as a team and shared between members to design class diagrams. I am responsible for class diagram of Forum.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

07.04.2023

**Comment by AliBasarann** [comment]
I didn't see any deficiency in your class. If you think that the class is completed, we can close the issue.

**Comment by halisbal** [comment]
Since the task is done and reviewed, I am closing this issue.
