### ISSUE TITLE
Initializing README Document of the Backend

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#470]
### Description

I'll be creating a README document which briefly explains what every layer in the project do and how it works. As a team we thought it will be a beneficial feature both for team members and general look of the repository.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

24.10.2023 - Tuesday - 23.59

**Comment by UnalDeniz** [comment]
I've checked the readme. It has a clear structure, and you've explained the layers quite well. Only thing that comes to my mind to improve the readme would be adding a small section that explains how to get it running.

**Comment by canuzdrn** [comment]
Thanks for your feedbacks, you may visit the updated [README](https://github.com/bounswe/bounswe2023group5/blob/main/app/backend/README.md)

**Comment by UnalDeniz** [comment]
I've checked it again. You've done a great job. I am closing this issue.
