### ISSUE TITLE
Designing Class Diagram: User

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#48]
### Description

The class diagrams are shared among the team, I will design class diagram of user. 

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

07.04.2023

**Comment by halisbal** [comment]
I reviewed the work and everything is perfect. Good work! @zeynep-baydemir . Since you are done with this task, I am closing this issue.
