### ISSUE TITLE
Handling the Empty Submit in Forgot Password Route

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#492]
### Description

When I am working on #451 I realized that the frontend allows to submit empty email field. Although it is handled appropriately at the backend, we should not send the request with empty email field. 

### 👮‍♀️ Reviewer

Deniz Ünal
### ⏰ Deadline

24.10.2023

**Comment by AliBasarann** [comment]
I realized that this problem stems from that we used single form for both email verification and getting the verification code. We can use seperate forms for fixing this problem.

**Comment by UnalDeniz** [comment]
This issue is already merged, so I am closing this issue now.
