### ISSUE TITLE
Deploy Frontend To AWS

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#495]
### Description

We should create create an AWS EC2 instance, set up the necessary environment, and deploy our frontend project within a Docker container using existing Dockerfile.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

28.10.2023

**Comment by AliBasarann** [comment]
I will push the docker image to dockerhub and deploy the frontend to aws.

**Comment by AliBasarann** [comment]
I deployed the frontend of the application to aws. This is the [link](http://ec2-51-20-78-40.eu-north-1.compute.amazonaws.com) of the frontend.

**Comment by cisel-zumbul** [comment]
Nice and working, good job!
