### ISSUE TITLE
Games Page Implementation - MOBILE

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#497]
### Description

We should implement games page for mobile with the following functionalities:

- Users see all games available listed
- Users search games by tags such as genre, production, player
- Users filter games by tag such as genre, production player

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

31.10.2023

**Comment by harunsami** [comment]
@egeek259 and I implemented the games page with all necessary functionalities. @bilalatim  can you review our work and close this issue.

**Comment by bilalatim** [comment]
The games page is quite nice. fulfills the required functionality. So I'm closing this thread.
