### ISSUE TITLE
Determining the Primary, Secondary, Background, Text and Dark Text Colors

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#498]
### Description

We need to choose the colors for Primary, Secondary, Background, Text and Dark Text from our color palette.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

26.10.2023

**Comment by alperen-bircak** [comment]
I propose we use these colors from our palette as the theme defaults
 `$color-primary: $blue-green;
$color-primary-dark: $prussian-blue;
$color-secondary: $yellow;
$color-accent: $orange;
$color-container: $sky-blue;
$color-background: $vanilla-light-80;
$color-text: $prussian-blue-dark-50;
$color-text-light: $vanilla-light-50;`

**Comment by AliBasarann** [comment]
I will open a poll, which includes these colors, to in the frontend channel of our discord channel.

**Comment by AliBasarann** [comment]
According to the poll results we decided to use the colors that Alperen suggested. So, I am closing the issue.
