### ISSUE TITLE
Connecting Login Page to Endpoint - MOBILE

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#506]
### Description

We need to set up the necessary connections for the mobile to communicate with the backend. This will enable data retrieval, submission, and synchronization between the backend and the mobile of the application. I am responsible of connecting Login page to its endpoint.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

31.10.2023

**Comment by harunsami** [comment]
I have connected the login page to back-end endpoints. @said-yolcu  can you review my work and close this issue.

**Comment by said-yolcu** [comment]
I have reviewed your login page. It meets the requirements. Nice work @harunsami .
