### ISSUE TITLE
Connecting Delete Account Page to Endpoint - MOBILE

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#507]
### Description

We need to set up the necessary connections for the mobile to communicate with the backend. This will enable data retrieval, submission, and synchronization between the backend and the mobile of the application. I am responsible of connecting Delete Account page to its endpoint.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

31.10.2023

**Comment by harunsami** [comment]
I have connected the delete account page to back-end endpoints. @bilalatim  can you review my work and close this issue.

**Comment by bilalatim** [comment]
Since you have successfully connected the endpoints, I am closing this issue.
