### ISSUE TITLE
Connecting Logout Functionality To The Backend Endpoint - MOBILE

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#509]
### Description

I will connect the log-out functionality I have created to the endpoints created by the Backend team. This issue is the logical completion of #463 .

### 👮‍♀️ Reviewer

Harun Sami Çelik

### ⏰ Deadline

31.10.2023 - Tuesday - 23.59

**Comment by said-yolcu** [comment]
I have connected the log-out functionality to back-end endpoints. @harunsami can you review my work and close this issue.

**Comment by harunsami** [comment]
I checked your work. Nice job. I am closing this issue.
