### ISSUE TITLE
Designing Class Diagram: Report

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#51]
### Description

The class diagrams are shared among the team members, I will design the class diagram of **Report**.

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

07.04.2023 - Friday 23.59

**Comment by zeynep-baydemir** [comment]
Diagram is detailed and well designed. Thank you for good work. There is nothing more to be added, so I'm closing this issue.
