### ISSUE TITLE
Connecting Change Password Page To The Backend Endpoints - MOBILE

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#510]
### Description

In #465 I have created a Change Password Page for Mobile. Now I will connect it to the endpoints created by the Backend team.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

31.10.2023 - Tuesday - 23.59

**Comment by said-yolcu** [comment]
I have connected **Change Password** page to back-end endpoints. @egeek259 can you review my work and close this issue.

**Comment by egeek259** [comment]
I have reviewed your work, everything seems fine. Closing this issue
