### ISSUE TITLE
Implementing Authorization Middleware for Backend

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#513]
### Description

Authorization middleware should be implemented for the backend part. If authorization required, it should check the authorization token's validity and return the user connected to the HTTP request if the token is valid.

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

31.10.2023 - Tuesday - 23.59

**Comment by zeynep-baydemir** [comment]
I tried it and it works properly and it has great functionality, thank you for your work.
