### ISSUE TITLE
Deployment Backend to AWS

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#515]
### Description

I will deploy the backend to AWS.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

31.10.2023

**Comment by UnalDeniz** [comment]
The backend is up and running on http://ec2-16-16-166-22.eu-north-1.compute.amazonaws.com/ @halisbal can you check it?

**Comment by halisbal** [comment]
Thanks for letting us know that the backend has been successfully deployed to AWS, and it's up and running at http://ec2-16-16-166-22.eu-north-1.compute.amazonaws.com/.

I've double-checked the server as well, and it looks great from my end too. If you encounter any issues or need further assistance in the future, please don't hesitate to reach out.

I'll go ahead and close this issue now. If you have any more updates or if there are any additional tasks related to this deployment, feel free to open a new issue or let us know.

Thanks again for your hard work on this!
