### ISSUE TITLE
Adding conventions to the wiki page

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#517]
### Description

We hneed to gather the conventions we decided on to the wiki page so tht they can be easily viewed and updated.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

30.10.2023

**Comment by alperen-bircak** [comment]
I have added the page to the wiki, all the teams are encourgaed to update their conventions as new ones arise. I have also added the branch name convention that we had discussed.

**Comment by cisel-zumbul** [comment]
It looks decent and same as we have discussed, it'd just be better if you'd tell me that I was a reviewer of this issue a bit earlier :)
