### ISSUE TITLE
Connecting Home Page to Backend - Mobile

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#519]
### Description

Connect home page to backend

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

31.10.2023

**Comment by bilalatim** [comment]
@said-yolcu , can you close this issue because I connected my home page to the backend? You can check [#570](https://github.com/bounswe/bounswe2023group5/pull/570)

**Comment by said-yolcu** [comment]
I checked and saw that you have indeed connected the home page to backend. Well done! I am closing this issue and marking it as done.
