### ISSUE TITLE
Designing Use Case Diagram : Report

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#52]
### Description

The user case diagrams are shared among the team members, I will design the use case diagram of **Reporting System**.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by Ardakacd** [comment]
Your use cases are nice and detailed, because of that I am closing the issue.
