### ISSUE TITLE
Connecting Signup to Backend - Mobile

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#520]
### Description

Connecting Signup to Backend - Mobile

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

31.10.2023

**Comment by bilalatim** [comment]
I connected the register page to the backend with that ssh key 0ef419ba8bac806605a0807fe96a5c39afa6ed01 commit. Can you check @said-yolcu ?

**Comment by said-yolcu** [comment]
I checked the apk and saw that you have indeed connected the register page to the backend. I am closing this issue and marking it as done.
