### ISSUE TITLE
Build Apk For the Mobile App - Mobile

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#522]
### Description

Build apk file for the mobile app and test it.

### 👮‍♀️ Reviewer

Harun Sami

### ⏰ Deadline

31.10.2023

**Comment by bilalatim** [comment]
@harunsami can you check [release0.0.1](https://github.com/bounswe/bounswe2023group5/releases/tag/Group5-Mobile-App-v1.0.0)

**Comment by harunsami** [comment]
I checked the apk. Nice job. I'm closing this issue.
