### ISSUE TITLE
Determining the Name of the Project

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#539]
### Description

Explore and finalize a fitting name for the project that captures its essence and appeals to the target audience.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

31.10.2023

**Comment by cisel-zumbul** [comment]
A poll to gather candidate platform names is shared with the group. It is accessible over [here](https://forms.gle/7YDWiCAM6iHGTzJQ8).

**Comment by cisel-zumbul** [comment]
After gathering the ideas through the form above, now we'll be voting them with this [poll](https://forms.gle/eUWiQHnZWBnDcAXi6).

**Comment by cisel-zumbul** [comment]
As results show, our platform name is voted to be Game Guru ! !
