### ISSUE TITLE
Determining the Branch Naming

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#541]
### Description

Establish a consistent naming convention for the project's branches to ensure clarity and ease of collaboration among team members.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

31.10.2023

**Comment by cisel-zumbul** [comment]
I think we've already established this and it is written in the [conventions page](https://github.com/bounswe/bounswe2023group5/wiki/Conventions).
