### ISSUE TITLE
Preparing a summary of the project status and any changes that are planned for moving forward

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#542]
### Description

Compile an overview of the current project status, outlining progress, blockers, and any future alterations to the initial plan.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

31.10.2023

**Comment by Ardakacd** [comment]
I added summary of project status and changes moving forward. You can reach it from [here](https://github.com/bounswe/bounswe2023group5/wiki/CMPE-451-Milestone-1-Report). @canuzdrn can you review?

**Comment by canuzdrn** [comment]
* Project status is written in detail and pretty accurately
* Changes we are planned on our forward progress is pretty realistic and consists of premises we are discussed about as a team
Summary of the project status and changes moving forward looks good to me, thanks a lot for the good work !
