### ISSUE TITLE
Preparing evaluation of the status of deliverables and its impact on your project plan (reflection)

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#546]
### Description

Assess the progress and status of each deliverable, reflecting on how they align with the project plan and any subsequent adjustments needed. We assign 3(one member each) to evaluate their progress.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

31.10.2023

**Comment by halisbal** [comment]
I prepared the evaluation of the status of deliverables and its impact on our project plan part for the milestone report, and  added it to the wiki page that we created. [Here](https://github.com/bounswe/bounswe2023group5/wiki/CMPE-451-Milestone-1-Report) you can reach to the milestone report.

**Comment by canuzdrn** [comment]
Evaluation of the status of the deliverables seems pretty accurate and written in detail. Also thanks for connecting relevant issues into the corresponding subsection, great documenting according to good practices !
