### ISSUE TITLE
Designing Class Diagram: Game

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#55]
### Description

The class diagrams are shared among the team members, I will design the class diagram of Game. The class diagram should contain the attributes and methods of the game class.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

07.04.2023 - Friday - 23:59

**Comment by bilalatim** [comment]
I shared the draft of the **Game class diagram** with @said-yolcu via the discord link. Can I get your comments about the game class diagram, @said-yolcu ?

**Comment by said-yolcu** [comment]
I prepared a review report for the **Game class diagram** and shared it with @bilalatim via discord.

**Comment by bilalatim** [comment]
I reviewed the review report you prepared for the game class diagram. I edited the titles below. Can you review your final version again, @said-yolcu. Is there something I missed? If ı don' miss anything, please close this issue.

- [ ] While creating the game, the game ID should not be given as a parameter to the function, the gameId should be used by increasing it automatically.
- [ ] Reporting games function added.
- [ ] The removeGameIcon function did not added because a game always must have an icon. Instead of that I add changeIcon function.

**Comment by said-yolcu** [comment]
I re-reviewed the **Game Class Diagram** you have prepared. Great job. It meets all the requirements. I am closing this issue and marking it as **Done**.
