### ISSUE TITLE
Implementing create-game endpoint

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#557]
### Description

In order to show games in our website, there needs a functionality to create them. This endpoint will manage that.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

14.11.2023

**Comment by UnalDeniz** [comment]
this endpoint is postponed to second milestone

**Comment by Ardakacd** [comment]
I reviewed the endpoint implementation. I also use this endpoint in frontend. Everything looks fine. So I'm closing the issue.
