### ISSUE TITLE
Designing Class Diagram: Group

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#56]
### Description

The class diagrams are shared among the team members, since we worked on groups together so far, we will design the class diagram of Groups.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

07.04.2023

**Comment by bilalatim** [comment]
I reviews the Group class you prepared. Nice work, it has almost everything to meet our requirements. I just want to ask, is it possible to add isPrivate attribute instead of using tags for private groups?

**Comment by cisel-zumbul** [comment]
Actually, we had designed the class so that privacy of the groups are checked via Membership Policy attribute instead of using tags. In this case, we also won't be needing a isPrivate attribute.

**Comment by cisel-zumbul** [comment]
Our class diagram is reviewed by team members and approved. Therefore I'm closing this issue.
