### ISSUE TITLE
Login page sends email field even if an username is entered

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#566]
### Description

When logging in to the site, the field says email or username, but the sent value is always an email. We need to either change the text on the field, or change what we send to backend.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

31.20.2023

**Comment by AliBasarann** [comment]
The backend only accepts the email as input for now. I am changing the text on the field.

**Comment by AliBasarann** [comment]
I edited the text field accordingly.
