### ISSUE TITLE
Designing Use Case Diagram: Groups

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#57]
### Description

The use case diagrams are shared among the team members, since we worked on groups feature together so far, we will design the class diagram of Groups too.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

08.04.2023

**Comment by cisel-zumbul** [comment]
After a long and careful consideration, we have decided our use case diagram will follow the rules explained [here](https://www.educative.io/answers/what-are-include-and-extend-relationships-in-a-use-case-diagram) as it complies with schemas in lecture slides and provides a clear example. The link has been also shared with the team through our discord channel.

**Comment by AliBasarann** [comment]
I reviewed your class diagram. Your diagrams are very comprehensive and includes all necessary materials we need for now, so I am closing the issue. Thanks for your contribution.
