### ISSUE TITLE
Designing Class Diagram: Tag

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#58]
### Description

The class diagrams are shared among the team members, I will design the class diagram of Tag.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

07.04.2023 -Friday 23.59

**Comment by Ardakacd** [comment]
Wow, that a good point. I didn't know that. Now I fixed it, you can check and if there is no other problem you can close the issue.

**Comment by canuzdrn** [comment]
There is nothing to add on my side, thanks for the good work !
Hence @Ardakacd is done with class diagram of **Tag** I'm closing the issue
