### ISSUE TITLE
Designing Use Case Diagram: Event

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#59]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram of Event.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

08.04.2023 - Saturday - 23.59

**Comment by bilalatim** [comment]
I examined the use case diagram of Event you prepared. It was a simple and understandable work. There are no errors or omissions. You can close this issue.

**Comment by Ardakacd** [comment]
I'm closing the issue.
