### ISSUE TITLE
Create Presentation Slide 

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#593]
### Description

For milestone 1 presentations we need to prepare a slide presentation containing brief introduction and progress steps. 

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

31.10.2023 15:15

**Comment by cisel-zumbul** [comment]
Our presentation is ready and is accessible over [here](https://docs.google.com/presentation/d/1fiTUJOE1p8rMjqKeQymwNh5os_6_yuHtkR0zrbk87IA/edit?usp=sharing).

**Comment by AliBasarann** [comment]
It is a pretty good description. I liked it. I am closing the issue.
