### ISSUE TITLE
Deciding A Regular Meeting Time

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#6]
At the first meeting #1, we decided to set a regular meeting time. For this purpose, a survey will be organized to see the results of the collective voting done by the group. All group members can fill in the form by ticking the appropriate time intervals. The common time slot with the most votes will be determined as the next regular meeting time. You can access the survey at this [survey link](https://www.when2meet.com/?19044221-P1liU).

## Voters

- [x] Ali Başaran
- [x] Alperen Bırçak
- [x] Arda Kabadayı
- [x] Bilal Atım
- [x] Can Uzduran
- [x] Çisel Zümbül
- [x] Deniz Ünal
- [x] Ege Ekşi
- [x] Halis Bal
- [x] Harun Sami Çelik
- [x] Mehmet Said Yolcu
- [x] Zeynep Baydemir

@halisbal can you identify the weekly moderators and note-takers?

**Comment by halisbal** [comment]
I made a poll to identify individuals who are not interested in serving as moderators or note takers during our regular meetings. Using the feedback I received, I randomly assigned the roles of weekly moderators and note takers. 

You can see the assigned moderators and note takers for each week by referring to the image provided below.

![image](https://user-images.githubusercontent.com/83141387/223083888-5749f09e-44a1-40bd-bff6-afdf73b277ce.png)

**Comment by bilalatim** [comment]
* Thank you to all our members for completing the survey. As a result of the survey, **the regular meeting time** was determined as **19:00-20:00 on Thursday**. 
* In addition to the regular meeting hours, the roles of the weekly moderators and note takers were shared with other group members through communication channels and briefings were made.

**Comment by bilalatim** [comment]
This issue has been closed as it has been decided that the regular meeting time will be face to face on Thursday between 19:00-20:00 and who will be the weekly meeting moderators and note takers.
