### ISSUE TITLE
Writing 'Requirements Addressed In This Milestone' Section In Milestone 1 Report

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#604]
### Description

We need to explain the requirements that are addressed in Milestone 1 in its report. I'll prepare this section.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

03.11.2023

**Comment by UnalDeniz** [comment]
I've reviewed the section. It seems accurate. Good job.
