### ISSUE TITLE
RAM Control 

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#605]
### Description

I'll run the last checks on the RAM and make sure that everybody is filled their part.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

03.11.2023

**Comment by canuzdrn** [comment]
RAM screenshot and contents of the RAM doc is updated can you check when you are available from [here](https://github.com/bounswe/bounswe2023group5/wiki/RAM). @cisel-zumbul

**Comment by cisel-zumbul** [comment]
I made sure that everybody is added their part to RAM, that it was ready and its screenshots were updated before the deadline.
