### ISSUE TITLE
Preparing The Evaluation Of Tools And Processes Used To Manage The Project

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#606]
### Description

I will prepare an **evaluation** of **tools and processes** that are used by the team to manage the project. This evaluation will be part of the deliverables for the first milestone.

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

03.11.2023 - Friday - 12.00

**Comment by said-yolcu** [comment]
I have created a document for **evaluation of tools and processes used to manage the project**. @zeynep-baydemir , can you review the document I have sent to you and share your feedbacks with me?

**Comment by zeynep-baydemir** [comment]
I have read your part in [Milestone1 Report](https://github.com/bounswe/bounswe2023group5/wiki/CMPE-451-Milestone-1-Report). It contains all necessary parts and it is explanatory. Thank you for your work.
