### ISSUE TITLE
Updating Sequence Diagrams

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#607]
### Description

I will update the sequence diagrams according to changes in our project.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

03.11.2023

**Comment by zeynep-baydemir** [comment]
I added domain specific parts and removed event related parts and updated some parts according to our implementation. It can be reached from [here](https://drive.google.com/file/d/1SSdj3pSVKMcmLpkmNDtjVLglTVYd77Pw/view?usp=sharing). Can you review it @bilalatim.

**Comment by bilalatim** [comment]
Can you write directly the parts you changed so that I can check better? @zeynep-baydemir

**Comment by zeynep-baydemir** [comment]
I have changed login and register, deleted event related diagrams, added tag and avatar, added tag to game.

**Comment by bilalatim** [comment]
I checked the changes you made, @zeynep-baydemir, You made changes suitable for our project. Therefore, i close this issue.
