### ISSUE TITLE
Update Use Case Diagram

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#614]
### Description

Due to changes in requirements, we needed to update our use case diagram and this task was given to me.

### 👮‍♀️ Reviewer

Çisel

### ⏰ Deadline

3.11.2023

**Comment by bilalatim** [comment]
I update use case diagram. @cisel-zumbul  can you check it? You can access from [here](https://drive.google.com/file/d/1B9RkoZ0AM0ug1YiA1LCTpVhnZYyMDA-W/view?usp=sharing)

**Comment by bilalatim** [comment]
I also update our use case diagram page you can also check it.

**Comment by cisel-zumbul** [comment]
According to this diagram, non-registered users can view event page, registered users can see other registered users' joined event from his profile, admins can remove events. We need to remove those since we do not including events to our platform anymore.

**Comment by bilalatim** [comment]
I made the necessary changes. Can you check again? from [here](https://drive.google.com/file/d/1B9RkoZ0AM0ug1YiA1LCTpVhnZYyMDA-W/view?usp=sharing)

**Comment by cisel-zumbul** [comment]
It looks very nice and in alignment with the requirements, good job!
