### ISSUE TITLE
Implementing CI/CD for Frontend

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#624]
### Description

CI/CD pipeline for our frontend part of the repository should be implemented via GitHub Actions.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

29.10.2023

**Comment by AliBasarann** [comment]
Due to time constraints I cannot implemented the ci/cd for the frontend

**Comment by AliBasarann** [comment]
Due to time constraints I could not implemented the ci/cd for the frontend.
