### ISSUE TITLE
Forum Post Functionality Implementation - MOBILE

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#625]
I will be responsible for the functionality implementation of the forum post feature in our mobile application.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

12.11.2023

**Comment by bilalatim** [comment]
@egeek259 can you check my work?

**Comment by egeek259** [comment]
I have checked your work, everything is okay. Closing this issue.
