### ISSUE TITLE
Designing Class Diagram: Post

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#63]
### Description

The class diagrams are shared among the team members, I will design the class diagram of Post.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

2023-04-08 Saturday 23.59

**Comment by AliBasarann** [comment]
I reviewed your diagram. I saw that there is a tag list. Yet, there is no function to edit this list. I believe that if there would be a function to add tags and a function to remove tags, it would be better. In addition, it can be good if the class have a function to get comments because we need to get the comments of the post if the comment button of the button is clicked.

**Comment by UnalDeniz** [comment]
> I reviewed your diagram. I saw that there is a tag list. Yet, there is no function to edit this list. I believe that if there would be a function to add tags and a function to remove tags, it would be better. In addition, it can be good if the class have a function to get comments because we need to get the comments of the post if the comment button of the button is clicked.

I've added the necessary methods to class diagram. Please check if it is okay now.

**Comment by halisbal** [comment]
I checked your class diagram while designing my sequence diagram for forum. I remember that we added some requirements for moderators that provides functionality for them to lock or flag posts. We could add these two functions to the class diagram as "lockPost" and "flagPost". Also we could add two new fields as "is_locked" and "is_flagged".

**Comment by UnalDeniz** [comment]
> I checked your class diagram while designing my sequence diagram for forum. I remember that we added some requirements for moderators that provides functionality for them to lock or flag posts. We could add these two functions to the class diagram as "lockPost" and "flagPost". Also we could add two new fields as "is_locked" and "is_flagged".

I've added the  fields and methods you've mentioned and created getter methods for both fields.

**Comment by AliBasarann** [comment]
I reviewed the class diagram again and it seems okay for me. Because there is no changes in the diagram I am closing the issue.
