### ISSUE TITLE
Designing Class Diagram: Comment

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#64]
### Description

The class diagrams are shared among the team members, I will design the class diagram of Comment.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

2023-04-08 Saturday 23.59

**Comment by UnalDeniz** [comment]
@said-yolcu I've finished on working  the class diagram, can you review it?

**Comment by said-yolcu** [comment]
I have reviewed the the **Comment Class Diagram** @UnalDeniz sent to me. Good job @UnalDeniz. The class diagram you have prepared meets all the requirements. I am closing this issue and marking it as done.
