### ISSUE TITLE
Create Review Component - FE

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#644]
### Description
We will create a component  for displaying reviews, and also voting on them. These will be displayed in the individual game pages.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

13.11.2023 - Monday - 23.59

**Comment by cisel-zumbul** [comment]
PR related to this issue is reviewed and closed, therefore closing this issue as done
