### ISSUE TITLE
Designing Class Diagram: Review

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#65]
### Description

The class diagrams are shared among the team members, I will design the class diagram of **Review**. The class diagram should contain the attributes and methods of the **Review class**.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

07.04.2023 - Friday - 23:59

**Comment by bilalatim** [comment]
I shared the draft of the review class diagram with @said-yolcu  via the discord link. Can I get your comments on the review class diagram, @said-yolcu ?

**Comment by said-yolcu** [comment]
I prepared a review report for the **Review class diagram** and shared it with @bilalatim via discord.

**Comment by bilalatim** [comment]
I reviewed the review report you prepared for the Review class diagram. I edited the titles below. Can you review your final version again, @said-yolcu . Is there something I missed? If ı don' miss anything, please close this issue.

- [ ] While creating the Review, the reviewID should not be given as a parameter to the function, the reviewID should be used by increasing it automatically.
- [ ] The getUserProfilePhoto and getUserName functions were not deleted because we share the user profile photo and username information on the Review page.
- [ ] Instead of assigning setters to upvote and downvote, we can directly put upvote and downvote functions. After all, a user can give a maximum upvote to a review. In this case we need to provide all four functions: upvote, undoUpvote, downVote, undoDownvote. These four functions were used instead of setVoteFunctions.

**Comment by said-yolcu** [comment]
Nice job @bilalatim . The **Review Class Diagram** you have prepared meets the requirements. I am closing the issue and marking it as done.
