### ISSUE TITLE
Designing Class Diagram: Promotion

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#66]
### Description

The class diagrams are shared among the group members. My duty is to design the class diagram for **Promotion**.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

08.04.2023 - Saturday - 23.59

**Comment by bilalatim** [comment]
Good job, the Class Diagram for Promotion you have prepared meets all the requirements we have set for the Promotion. I'm closing this issue because your task completed.
