### ISSUE TITLE
Adding Notes of Meeting #6

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#67]
### Description

I was the note taker of the meeting 6 (06.04.2023). I will upload the notes of the meeting to the wiki page and clarify what we decided and did. [Meeting note template](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-Note-Template) will be used to be consistent.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

2023-04-10 Monday 23.59

**Comment by bilalatim** [comment]
@UnalDeniz  I'm closing this issue for adding the **[Meeting #6 Notes](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-%236-Notes-06.04.2023)** to the github wiki.
