### ISSUE TITLE
Designing Use Case Diagram: Promotion

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#68]
### Description

The use case diagrams are shared among team members. My duty is to design the use case diagram for **Promotion**.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

08.04.2023 - Saturday - 23.59

**Comment by said-yolcu** [comment]
I have designed the **Use Case Diagram for Promotion** and shared it with @bilalatim . @bilalatim can you review the design and give me feedback.

**Comment by bilalatim** [comment]
Use Case Diagram for Promotion looks good and matches with requirements. Couldn't find anything to add, therefore I'm closing this issue.
