### ISSUE TITLE
Designing Use Case Diagram: Game

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#69]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram of Game. In order to prepare a use case diagram, I will make a design suitable for the slides of the lesson and the Game mockups prepared before #39 .

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

08.04.2023 - Saturday - 23:59

**Comment by bilalatim** [comment]
I prepared a draft of the **Use Case Diagram for Game** and shared it with @cisel-zumbul via discord. Can I get your comments about the use case diagram @cisel-zumbul ?

**Comment by cisel-zumbul** [comment]
I reviewed it and left a small note on the diagram. Other than that, it looks pretty good.
