### ISSUE TITLE
Implementing Sorting of Reviews

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#692]
### Description

We need to implement sorting and filter of reviews in frontend in alignment with the requirements:

 - Users should be able to sort reviews by date
 - Users should be able to sort reviews by upvote ratio

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

20.11.2023

**Comment by cisel-zumbul** [comment]
With the backend team, we concluded that filtering by vote is not necessary or valuable since we already have the option to sort by vote. As a result, we removed it from the requirements and therefore from the task.
