### ISSUE TITLE
Implementing image uploading functionality

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#698]
### Description

There will be a service that takes the image from backend, saves to server and return the path in the server. This is needed to save icons for games, users, posts, etc. I will also add this service to create and edit enpoints for the related endpoints.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

21.11.2023

**Comment by AliBasarann** [comment]
I checked the service, it works fine. I am closing the issue.
