### ISSUE TITLE
Restructuring Project Folder Layout - MOBILE

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#699]
### Description

This issue focuses on revamping the current project folder structure for mobile, for improved clarity and efficiency . The plan involves creating new folders and reorganizing existing files into these folders. This change aims to streamline file navigation, enhance maintainability, and support future scalability of the project

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

21.11.2023

**Comment by egeek259** [comment]
@said-yolcu can you review this issue?

**Comment by said-yolcu** [comment]
I have seen the new layout. It is practical . Nice job.
