### ISSUE TITLE
Designing Use Case Diagram: Review

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#70]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram of Review. In order to prepare a use case diagram, I will make a design suitable for the slides of the lesson and the Review mockups prepared before #31  .

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

08.04.2023 - Saturday - 23:59

**Comment by bilalatim** [comment]
I prepared a draft of the **Use Case Diagram for Review** and shared it with @cisel-zumbul via discord. Can I get your comments about the use case diagram @cisel-zumbul ?

**Comment by cisel-zumbul** [comment]
It looks good and matches with requirements. Couldn't find anything to add, therefore I'm closing this issue.
