### ISSUE TITLE
Annotation Research - MOBILE

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#702]
### Description

Our application will give opportunity to annotate texts to the users. We need to research how to implement annotation feature.

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

21.11.2023

**Comment by egeek259** [comment]
After thorough research on implementing text annotation features for our mobile application,I have gathered valuable insights and strategies. I will be informing my teammates about those insights.We will be well-equipped to move forward with designing and integrating this feature into our application.

**Comment by said-yolcu** [comment]
I have reviewed your research . Nice job.
