### ISSUE TITLE
Review And Edit Controller Scripts - MOBILE

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#708]
### Description

I will review and edit controller scripts for mobile part of the project.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

16.11.2023 - Monday - 23.59

**Comment by bilalatim** [comment]
@said-yolcu you have made the necessary edits in the controller scripts. I merged its PR into main.

**Comment by said-yolcu** [comment]
The code relating to this issue is merged to main. @egeek259 , can you review and close this issue.

**Comment by egeek259** [comment]
I have reviewed it, everything seems fine, merging.
