### ISSUE TITLE
Create Request Functions For Game Controller Endpoints - MOBILE

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#709]
### Description

I will create the necessary functions to perform requests to the game controller endpoint.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

19.11.2023 - Sunday - 23.59

**Comment by said-yolcu** [comment]
@bilalatim , the branch of this issue is merged to the main branch with pr #737 . Can you close this issue?

**Comment by bilalatim** [comment]
I'm closing this issue because you've completed your work.
