### ISSUE TITLE
Connecting the Classes and Completing the Class Diagram

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#71]
### Description

The class diagrams are shared among the team members. While team members completeing the classes, I will be connecting the classes and checking the coherence between them. 

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

08.04.2023

**Comment by UnalDeniz** [comment]
I reviewed the connection between diagrams. Everything seems as it should be. I'm closing this issue.
