### ISSUE TITLE
Edit and Delete Functionalities for Group - BE

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#714]
### Description

Besides creating and retrieving information about groups, we (and users of course) also need to be able to edit and delete groups. (e.g. : edit group can be used for changing the title of the group)

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

21.11.2023

**Comment by UnalDeniz** [comment]
As the correspondent PRs are already merged, and everything is working I am closing this issue now.
