### ISSUE TITLE
Fix Errors and Bugs in Authontications Pages - MOBILE

### ISSUE THREAD

**Issue by bilalatim** [bounswe/bounswe2023group5#716]
### Description

I will fix errors and bugs in authontications pages

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

16.11.2023

**Comment by bilalatim** [comment]
@egeek259 I solve Authontications bugs and errors. Can you check authontication part in our project, please?

**Comment by egeek259** [comment]
Everything seems fine, closing the issue.
