### ISSUE TITLE
Designing Use Case Diagram: Profile

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#72]
### Description

Use case diagrams are shared among team members. I will design the use case diagram for profile.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

08.04.2023

**Comment by cisel-zumbul** [comment]
Left a small note on the diagram, I think from his profile, user should see the events/games that he's already following instead of viewing them all.

**Comment by cisel-zumbul** [comment]
Now I checked and after modifications everything looks fine, thanks for your good work :) There is nothing more to do here, I'm closing this issue.
