### ISSUE TITLE
Deleting Unused Branches - MOBILE

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#720]
### Description

As we resolved various issues, several branches have become obsolete. I need to delete the unused branches.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

20.11.2023

**Comment by harunsami** [comment]
I deleted merged or unused branches related mobile development. You can close this issue @said-yolcu .

**Comment by bilalatim** [comment]
Everything seems fine, closing the issue.
