### ISSUE TITLE
Designing Use Case Diagram: Moderator

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#73]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram of moderator. Moderator checks the reports and evaluates them. Moderators also can delete posts, comments and ban users from the forum.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

08.04.2023

**Comment by egeek259** [comment]
Great work on designing the use case diagram for the moderator. I am closing this issue.
