### ISSUE TITLE
Designing Class Diagram: Annotation

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#74]
### Description

The class diagrams are shared among the team members, I am responsible of the design of the class diagram of Annotation.

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

08.04.2023 - Saturday - 23:59

**Comment by UnalDeniz** [comment]
I reviewed your diagram. I think there should be getter method for id field, also setCreatedBy method seems unnecessary since created_by field is set only once at the creation of the object.

**Comment by egeek259** [comment]
> I reviewed your diagram. I think there should be getter method for id field, also setCreatedBy method seems unnecessary since created_by field is set only once at the creation of the object.

I've made the necessary changes to class diagram. Please check if it is okay now.

**Comment by UnalDeniz** [comment]
It seems okay now. I am closing this issue.
