### ISSUE TITLE
Designing Class Diagram: Search

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#75]
### Description

The class diagrams are shared among the team members, I am responsible of the design of the class diagram of Search.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

08.04.2023 - Saturday - 23:59

**Comment by halisbal** [comment]
I think we don't need search comment function, I believe we didn't add that functionality in the requirements. Other than that, nice work!

**Comment by egeek259** [comment]
> I think we don't need search comment function, I believe we didn't add that functionality in the requirements. Other than that, nice work!

Thank you! I've removed that functionality from the class diagram. Please check if it is okay now.

**Comment by halisbal** [comment]
Now it is perfect! Thank you for considering my feedback. Since you are done with the class diagram of search, I am closing this issue.
