### ISSUE TITLE
Designing the Sequence Diagrams for Groups Feature

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#76]
### Description

 We should design the the sequence diagrams for the groups feature in accordance with the class and use case diagrams.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

10.04.2023

**Comment by cisel-zumbul** [comment]
We've completed and shared the diagram's link through _task1_ channel in our Discord group. Can you please review it @AliBasarann ?

**Comment by AliBasarann** [comment]
I reviewed the sequence diagrams. They include necessary sequences for now, so I am closing the issue.
