### ISSUE TITLE
Designing Sequence Diagram: Comment

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#77]
### Description

Sequence diagrams are shared among team members. I will design the sequence diagram for comments.

### 👮‍♀️ Reviewer

Ege Ekşi

### ⏰ Deadline

08.04.2023 Saturday 23.59

**Comment by egeek259** [comment]
I checked your sequence diagram. It is very clear and detailed. Since you are done with the sequence diagram of comment, I am closing this issue.
