### ISSUE TITLE
Designing Sequence Diagram: Report

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#79]
### Description

The sequence diagrams are shared among the team members, I will design the sequence diagram of Reporting System

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by halisbal** [comment]
I checked your diagram @canuzdrn. Everything looks fine, nice work! Since your task is done, I am closing this issue.
