### ISSUE TITLE
General test plan for the project

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#795]
### Description

General test plan for the project for Milestone 2.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

30.11.2023

**Comment by zeynep-baydemir** [comment]
I have added testing part for the backend. It can be reached from [here](https://github.com/bounswe/bounswe2023group5/wiki/CMPE-451-Milestone-2-Report)

**Comment by zeynep-baydemir** [comment]
Test plans have already added to milestone report. Therefore, i am closing this issue.
