### ISSUE TITLE
Adding Your Favorite Repositories To The Repository Research Page

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#8]
I created the repository research page where every team member should add their favorite github repositories. You can access the page from [here](https://github.com/bounswe/bounswe2023group5/wiki/Repository-Research). As an example, I added one repository. You can refer to it and add yours. 

As you contribute, you can check your name on the list.
- [x] Ali Başaran
- [x] Alperen Bırçak
- [x] Arda Kabadayı
- [x] Bilal Atım
- [x] Can Uzduran
- [x] Çisel Zümbül
- [x] Deniz Ünal
- [x] Ege Ekşi
- [x] Halis Bal
- [x] Harun Sami Çelik
- [x] Mehmet Said Yolcu
- [x] Zeynep Baydemir

**Comment by canuzdrn** [comment]
Since everyone is done with adding their research about a GitHub repository to the [research page](https://github.com/bounswe/bounswe2023group5/wiki/Repository-Research) of our repository, this issue may be closed.
