### ISSUE TITLE
Designing Sequence Diagram: Annotation

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#80]
### Description

Sequence diagrams are shared among team members. I will design the sequence diagram for annotation.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

08.04.2023 - Saturday - 23:59

**Comment by Ardakacd** [comment]
I checked your sequence diagram. It is very clear and detailed. Hence I'm closing the issue.
