### ISSUE TITLE
Modifying Forum Page With Agreed UI Design Decisions - MOBILE

### ISSUE THREAD

**Issue by said-yolcu** [bounswe/bounswe2023group5#801]
### Description

I will modify the forum page with agreed UI design decisions.

### 👮‍♀️ Reviewer

Harun Sami Çelik

### ⏰ Deadline

27.11.2023 - Monday - 23.00

**Comment by harunsami** [comment]
I checked your work. Modifications are sufficient for now. I am closing this issue.
