### ISSUE TITLE
Designing Sequence Diagram: Event

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#81]
### Description

The sequence diagrams are shared among the team members, I will design the sequence diagram of Event.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by AliBasarann** [comment]
I reviewed the event sequence diagram. I think that you created all necessary diagrams and there is nothing to add for now. I am closing the issue. Thanks for your contributions.
