### ISSUE TITLE
Designing Sequence Diagram: Authentication 

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#82]
### Description

The use case diagrams are shared among the team members, I will design the sequence diagram of Authentication such as login, register, change password and logout.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by halisbal** [comment]
I reviewed your work and observed that everything was as it should be. Good work! Since you are done with sequence diagram of authentication, I am closing this issue.
