### ISSUE TITLE
Designing Sequence Diagram: Post

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#84]
### Description

Sequence diagrams are shared among team members. I will design the sequence diagram for posts.

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

23.04.2023 Saturday 23.59

**Comment by zeynep-baydemir** [comment]
I checked your work, and everything looks perfect. Thank you for your detailed diagram. Because everything looks good, I am closing this issue.
