### ISSUE TITLE
Designing Use Case Diagram: Admin

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#85]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram of Admin. It will mostly include additional features Admins' have and how they use them.

### 👮‍♀️ Reviewer

Ali Başaran

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by AliBasarann** [comment]
I reviewed your work. You can add "delete post" case to the admin use case. I think you added all the necessary cases other than that.

**Comment by canuzdrn** [comment]
Thanks for your feedback, I've added **Delete Post** use case for **Admin**. You may check again for additional remarks you can add.

**Comment by AliBasarann** [comment]
I see nothing to add for now. I am closing the issue. Thanks for your contributions
