### ISSUE TITLE
Adding Notes of Milestone 1 Meeting

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#86]
### Description

We had an extra meeting this week to discuss more about milestone 1. I was the note taker of that meeting  (08.04.2023). I will upload the notes of the meeting to the wiki page and clarify what we decided and did. [Meeting note template](https://github.com/bounswe/bounswe2023group5/wiki/Meeting-Note-Template) will be used to be consistent.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

10.04.2023 Sunday 23.59

**Comment by cisel-zumbul** [comment]
Thanks for your detailed report. It looks good. I don't have any extra comment; therefore, closing this issue.
