### ISSUE TITLE
RAM and Communication Plan

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#87]
### Description

The deliverables of Milestone 1 are shared among team members. I will do RAM and Communication Plan parts. 

### 👮‍♀️ Reviewer

Mehmet Said Yolcu

### ⏰ Deadline

08.04.2023

**Comment by zeynep-baydemir** [comment]
I have added RAM and Communication Plan to Wiki page and sidebar. @said-yolcu Could you please review it?

**Comment by said-yolcu** [comment]
I reviewed the **RAM** and **Communication Plan** you have created. Nice job. As far as I can see, they show all the necessary information regarding their respective subjects. I am closing this issue and marking it as **Done**.
