### ISSUE TITLE
Designing Sequence Diagram: Moderator

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#88]
### Description

The sequence diagrams are shared among the team members, I will design the use case diagram of moderator. Moderator checks the reports and evaluates them. Moderators also can delete posts, comments and ban users from the forum.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

10.04.2023

**Comment by bilalatim** [comment]
@AliBasarann,  I checked and everything looks perfect.  Good work! Since you are done with the task, I am closing this issue.
