### ISSUE TITLE
Creating User Scenario For Sign Up

### ISSUE THREAD

**Issue by Ardakacd** [bounswe/bounswe2023group5#90]
### Description

In the one of my [previous task](https://github.com/bounswe/bounswe2023group5/issues/33)  I designed a mock up for sign up. Now I write a user scenario by using that mock up. User scenario should be descriptive and clear.

### 👮‍♀️ Reviewer

Alperen Bırçak

### ⏰ Deadline

10.04.2023 - Monday 23.59

**Comment by Ardakacd** [comment]
I finished the task. You can see the user scenario from [this link](https://github.com/bounswe/bounswe2023group5/wiki/Unregistered-User-Scenario:-Sign-Up). @alperen-bircak can you review?

**Comment by alperen-bircak** [comment]
Looks great! A very vital scenario for the project.
