### ISSUE TITLE
Creating User Scenario for the Guest User Who Searches for a Game

### ISSUE THREAD

**Issue by AliBasarann** [bounswe/bounswe2023group5#91]
### Description

A user scenario is an important exercise for understanding the user and what they want from a product. It helps us to understand the intent, motivation, and context of an app’s users. I made a mockup for games page in my [previous assignment](https://github.com/bounswe/bounswe2023group5/issues/39). Now I will make a scenario for a guest user who searches for a game.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

10.04.2023

**Comment by canuzdrn** [comment]
It seems very detailed and aestheticly pleasent to me ! There is nothing to add on my side, thanks for the good work. Since, @AliBasarann is done with creating user scenario for the guest user who searches for a game, I'm closing this issue.
