### ISSUE TITLE
Creating User Scenario For Creating a Post After Viewing a Forum

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#92]
### Description

A user scenario is an important exercise for understanding the user and what they want from a product. It helps us to understand the intent, motivation, and context of an app’s users. In one of my previous tasks #40 , I designed a mock up for create post page. Now I will be writing a user scenario for a registered user to view a game forum and create a post.

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

10.04.2023

**Comment by bilalatim** [comment]
@halisbal , I checked and everything looks perfect. Good work! Since you are done with the task, I am closing this issue.
