### ISSUE TITLE
Preparing an API Documentation

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#932]
### Description

Although we have already a OpenAPI's Swagger documentation [here](http://ec2-16-16-166-22.eu-north-1.compute.amazonaws.com/swagger-ui/index.html#/), I will be preparing a detailed API documentation in order to express functionalities of endpoints that we are using throughout application.

### 👮‍♀️ Reviewer

Arda Kabadayı

### ⏰ Deadline

01.12.2023

**Comment by canuzdrn** [comment]
Prepared in detail API documentation can be seen from [here](https://github.com/bounswe/bounswe2023group5/wiki/API-Documentation).

**Comment by Ardakacd** [comment]
I reviewed the documentation. It seems good. So I'm closing.
