### ISSUE TITLE
Preparing a Report for Review Service Test

### ISSUE THREAD

**Issue by canuzdrn** [bounswe/bounswe2023group5#933]
### Description

* I've implemented the JUnit tests for review service methods as stated in #910 
* I will also prepare a test report for that

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

01.12.2023

**Comment by halisbal** [comment]
I checked the review service test reports in the milestone 2 report. I don't see any problem, thank you for your work! Since the task is done, I am closing this issue.
