### ISSUE TITLE
Merging All Use Case Diagrams Into One

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#96]
### Description

Each member of the team prepared some small parts of the use case diagram. Now we need to merge them into one use case diagram. While doing so, we should be careful to preserve existing relations while creating new relations between the different use cases. 

### 👮‍♀️ Reviewer

Zeynep Baydemir

### ⏰ Deadline

10.04.2023 23:59

**Comment by zeynep-baydemir** [comment]
Diagram looks good and reasonable. Thank you for your good work and effort. I am closing the issue because everything is okay.
