### ISSUE TITLE
Creating User Scenario For A User Viewing A Specific Group Page

### ISSUE THREAD

**Issue by cisel-zumbul** [bounswe/bounswe2023group5#98]
### Description

A user scenario is an important exercise for understanding the user and what they want from a product. It helps us to understand the intent, motivation, and context of an app’s users. I made a mockup for individual group page in #42. Now I will make a scenario for a user who looks for a specific group and views its individual page.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

10.04.2023 23:59

**Comment by cisel-zumbul** [comment]
Content has changed a little along the way. I made a mock-up for a user viewing the individual group page and then joining it. Can you have a look at it @halisbal ?

**Comment by halisbal** [comment]
I checked your work @cisel-zumbul , good work! The scenario is very detailed and shows the transitions between pages very clearly. Everything looks fine, so I am closing this issue.
