### ISSUE TITLE
Creating Missing Personal Information Page

### ISSUE THREAD

**Issue by harunsami** [bounswe/bounswe2023group5#99]
### Description

I should create my own personal page as soon as possible.

My Personal Information page should include:

* Name
* Surname
* Photo
* Brief description
* Skills
* Interests
* Contacts (GitHub, LinkedIn, Mail)

@bilalatim  can you review my page? 

### 👮‍♀️ Reviewer

Bilal Atım

### ⏰ Deadline

09.03.2023 - Sunday - 23:59

**Comment by harunsami** [comment]
I created my personal page. You can access the page with this [link](https://github.com/bounswe/bounswe2023group5/wiki/Harun-Sami-%C3%87elik).

**Comment by bilalatim** [comment]
I checked your personal information page. You have completed it in accordance with the template. I'm closing this issue as the task is complete.
